//! Archive read engine over libarchive (BSD-licensed C library, vendored as a git submodule at
//! `core/third_party/libarchive`, cross-compiled by this crate's own `build.rs` -- never a Cargo
//! dependency, so nothing about it appears in `cargo tree`/`cargo deny check`'s own dependency
//! graph; see `build.rs`'s own doc comment for why). M3.1's read path: [entries]/[read_entry]/
//! [filter_names] (part 1), all five compression backends `build.rs` vendors compiled in (lz4,
//! zstd, zlib, bzip2 and xz -- parts 2a-2e, each proven by a fixture pair under `core/fixtures/`
//! generated by `tools/fixtures/make_compression_fixtures.py`), the extraction [policy] ported from
//! the app's `ArchiveExtractionPolicy.kt` (part 3a), and [inspect]/[inspect_with_policy] plus the
//! streaming [extract] with runtime limits (part 3b), all over one seekable file descriptor.
//! M3.3 adds the browsing pair: [inspect_into] (the same header pass, writing the [listing] codec
//! into a caller-owned sink as each header is read) and [extract_entry_at] (one entry by header
//! ordinal, streamed, the pass stopping as soon as it is written). M3.4 adds the bulk path
//! (`docs/agent/DESIGN-M34-SELECTIVE-EXTRACT.md` section 2.5): [extract_blocks] streams every
//! selected entry -- by header ordinal ([Selection::Ranges]), path or all -- through a
//! [BlockSink] in one pass, telling a per-entry failure (a CRC or size mismatch, a decode error,
//! a header libarchive could not parse: the entry is lost, the pass goes on) from a fatal one (the
//! archive is dead: the pass aborts); [extract] and [extract_entry_at] are adapters over it, and
//! [inspect_for_extraction] is the header pass that gathers the selection's metadata for
//! [policy::evaluate_selection] first.
//!
//! **Input contract** (`docs/agent/DESIGN-M32-SEEKABLE-PFD.md` section 2.1): every public function
//! takes a raw fd that must refer to a regular file. The shared open path `fstat`s it and refuses
//! anything else with [ArchiveError::NotSeekable], then rewinds it to byte 0 -- a correctness
//! requirement, not hygiene: libarchive's fd reader seeks absolutely (`open_fd.c`) but treats the
//! first byte it reads as offset 0, so the seekable ZIP reader and 7z would read the wrong bytes
//! from a descriptor left at a non-zero offset. Pipes never reach the engine (the app stages
//! non-seekable input to cache first); `Reader::open_unchecked` exists for tests that want to
//! feed one anyway.

pub mod listing;
pub mod policy;

#[cfg(test)]
mod blocks_tests;
#[cfg(test)]
mod extract_tests;
#[cfg(test)]
mod listing_tests;
#[cfg(test)]
mod policy_tests;
#[cfg(test)]
mod seek_tests;

pub use policy::Decision;
pub use policy::EntryKind;
pub use policy::EntryMetadata;
pub use policy::Limits;

use std::collections::HashSet;
use std::ffi::CStr;
use std::fs::File;
use std::io::Seek;
use std::io::SeekFrom;
use std::io::Write;
use std::mem::ManuallyDrop;
use std::os::fd::AsRawFd;
use std::os::fd::BorrowedFd;
use std::os::fd::FromRawFd;
use std::os::raw::c_int;
use std::os::raw::c_void;
use std::os::unix::fs::FileTypeExt;
use std::os::unix::io::RawFd;

mod sys {
    //! Hand-written declarations for the small slice of libarchive's C API this crate calls --
    //! not machine-generated (no bindgen dependency pulled in for a couple of dozen stable,
    //! decades-old functions), and not exhaustive: extend this module rather than reaching for a
    //! `-sys` crate or bindgen wholesale, so this file stays the one place documenting exactly
    //! what is used and why. Every declaration below was checked against
    //! `core/third_party/libarchive/libarchive/archive.h`/`archive_entry.h` at v3.8.9.
    //!
    //! `LaSsizeT`/`LaInt64T` are libarchive's own portable typedefs (`archive.h`'s `la_ssize_t`/
    //! `la_int64_t`), guaranteed 64-bit on every platform including 32-bit ones, for large-file
    //! support. `Mode` (`archive_entry_filetype`/`archive_entry_perm`'s return type,
    //! `archive_entry.h`'s `__LA_MODE_T`) is `mode_t`, confirmed `unsigned int` (`c_uint`, 32-bit)
    //! on every target this crate builds for: the Android NDK sysroot's
    //! `asm-generic/posix_types.h` defines `__kernel_mode_t` as `unsigned int` for
    //! aarch64/armv7/x86_64 alike, and glibc matches on the host. `archive_entry_mtime` returns
    //! `time_t`, which is `long` -- **32-bit on `armv7-linux-androideabi`** (bionic) and 64-bit
    //! everywhere else this crate builds -- so it is declared `c_long`, never `i64`, and widened
    //! by the caller. Getting either width wrong on the 32-bit target would be a silent ABI
    //! mismatch, not a compile error -- confirmed against the real headers rather than assumed.
    use std::os::raw::c_char;
    use std::os::raw::c_int;
    use std::os::raw::c_long;
    use std::os::raw::c_void;

    #[repr(C)]
    pub struct Archive {
        _private: [u8; 0],
    }
    #[repr(C)]
    pub struct ArchiveEntry {
        _private: [u8; 0],
    }

    pub type LaSsizeT = isize;
    pub type LaInt64T = i64;
    pub type Mode = u32;
    pub type TimeT = c_long;

    unsafe extern "C" {
        pub fn archive_read_new() -> *mut Archive;
        pub fn archive_read_support_filter_all(a: *mut Archive) -> c_int;
        pub fn archive_read_support_format_all(a: *mut Archive) -> c_int;
        pub fn archive_read_open_fd(a: *mut Archive, fd: c_int, block_size: usize) -> c_int;
        pub fn archive_read_next_header(a: *mut Archive, entry: *mut *mut ArchiveEntry) -> c_int;
        pub fn archive_read_data(a: *mut Archive, buf: *mut c_void, len: usize) -> LaSsizeT;
        pub fn archive_read_data_block(
            a: *mut Archive,
            buff: *mut *const c_void,
            size: *mut usize,
            offset: *mut LaInt64T,
        ) -> c_int;
        pub fn archive_read_has_encrypted_entries(a: *mut Archive) -> c_int;
        pub fn archive_read_free(a: *mut Archive) -> c_int;
        pub fn archive_error_string(a: *mut Archive) -> *const c_char;
        pub fn archive_filter_count(a: *mut Archive) -> c_int;
        pub fn archive_filter_name(a: *mut Archive, n: c_int) -> *const c_char;
        pub fn archive_format(a: *mut Archive) -> c_int;
        pub fn archive_format_name(a: *mut Archive) -> *const c_char;

        pub fn archive_entry_pathname(e: *mut ArchiveEntry) -> *const c_char;
        pub fn archive_entry_hardlink(e: *mut ArchiveEntry) -> *const c_char;
        pub fn archive_entry_symlink(e: *mut ArchiveEntry) -> *const c_char;
        pub fn archive_entry_size(e: *mut ArchiveEntry) -> LaInt64T;
        pub fn archive_entry_size_is_set(e: *mut ArchiveEntry) -> c_int;
        pub fn archive_entry_filetype(e: *mut ArchiveEntry) -> Mode;
        pub fn archive_entry_perm(e: *mut ArchiveEntry) -> Mode;
        pub fn archive_entry_mtime(e: *mut ArchiveEntry) -> TimeT;
        pub fn archive_entry_mtime_is_set(e: *mut ArchiveEntry) -> c_int;
        pub fn archive_entry_is_data_encrypted(e: *mut ArchiveEntry) -> c_int;
        pub fn archive_entry_is_metadata_encrypted(e: *mut ArchiveEntry) -> c_int;
    }
}

const ARCHIVE_EOF: c_int = 1;
const ARCHIVE_OK: c_int = 0;
const ARCHIVE_WARN: c_int = -20;
/// `archive.h`'s "current operation cannot complete" (M3.4): for a header, "this header could not
/// be parsed, skip it"; for a data block, "this entry's data is wrong". The archive stays usable.
const ARCHIVE_FAILED: c_int = -25;

/// `archive.h`'s format-family mask and the one family code this crate needs to name (7-Zip,
/// whose encrypted-header failure is reported as [ArchiveError::Unsupported]).
const ARCHIVE_FORMAT_BASE_MASK: c_int = 0xff0000;
const ARCHIVE_FORMAT_7ZIP: c_int = 0xE0000;

/// `archive_entry.h`'s `AE_IFMT` and the file-type values this crate tells apart; every other
/// type (device nodes, fifos, sockets) is [EntryKind::Other].
const AE_IFMT: u32 = 0o170000;
const AE_IFREG: u32 = 0o100000;
const AE_IFLNK: u32 = 0o120000;
const AE_IFDIR: u32 = 0o040000;

/// One member of the simple listing ([entries]) and the value [DestinationProvider] is offered per
/// selected entry during [extract]. Unchanged since part 1; the richer per-entry shape is
/// [EntryMetadata], which [inspect] collects.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ArchiveEntry {
    pub path: String,
    pub size: i64,
    pub is_directory: bool,
}

impl ArchiveEntry {
    fn from_metadata(metadata: &EntryMetadata) -> Self {
        ArchiveEntry {
            path: metadata.path.clone(),
            // `archive_entry_size` reads 0 when the size is unset, which is what `uncompressed:
            // None` came from.
            size: metadata
                .uncompressed
                .and_then(|size| i64::try_from(size).ok())
                .unwrap_or(0),
            is_directory: metadata.kind == EntryKind::Directory,
        }
    }
}

#[derive(Debug)]
pub enum ArchiveError {
    /// `fstat` says the descriptor is not a regular file; the text names what it is
    /// (`"not seekable (fifo)"`). The app never sends one (non-seekable input is staged to cache
    /// first), so seeing this is a caller bug, not a user-facing condition.
    NotSeekable(String),
    /// libarchive could not recognise the input as any archive format it knows (no format bid at
    /// open: `archive_format() == 0`, "Unrecognized archive format"), or recognised a 7-Zip
    /// archive whose header is itself encrypted (the message contains "encrypted"), which this
    /// build cannot read. Distinct from [ArchiveError::Fatal] so the app can say "not an archive
    /// we can open" rather than "damaged".
    Unsupported(String),
    /// libarchive itself reported a fatal error mid-way; the message is `archive_error_string`'s
    /// own text. Also carries this crate's own few internal failures (`fstat`/`lseek`/destination
    /// write errors), each prefixed with what failed.
    Fatal(String),
    /// An entry's pathname was not valid UTF-8. Returned only by the exact-match lookups
    /// ([entries] and [read_entry]): an exact match against a lossily decoded name would be
    /// ambiguous, so those keep failing loudly until M3.7 gives legacy ZIP names a real charset.
    /// [inspect] and [extract] never return it -- they decode such a name with
    /// `String::from_utf8_lossy` and flag it with [EntryMetadata::name_lossy].
    NonUtf8Path,
    /// A runtime limit stopped the operation. `rule` names the limit: `"listing"`
    /// ([Limits::max_listing_entries], from [inspect]); `"entries"`, `"file"`, `"declared"` and
    /// `"total"` (from [extract]: [ExtractLimits::max_entries], [ExtractLimits::max_file_bytes], an
    /// entry's data exceeding its own declared size, [ExtractLimits::max_total_uncompressed_bytes]).
    /// `entry` is the path of the entry being processed when the limit hit.
    LimitExceeded { entry: String, rule: &'static str },
    /// [extract_entry_at] found no header at `ordinal` (a raw header index, [EntryMetadata::ordinal]),
    /// or the header there names a different path than the caller expected (`path` is what the
    /// caller asked for): the archive changed under a listing, or the id was forged. Carries both
    /// so the caller can say which entry.
    NotFound { ordinal: usize, path: String },
    /// libarchive reported `ARCHIVE_FAILED` for one entry -- a ZIP CRC or size mismatch at the end
    /// of its data, a header it could not parse -- so that entry is lost while the archive stays
    /// readable (M3.4). [extract_blocks] reports it through [BlockSink::failed] and continues;
    /// only the adapters that want part 3's all-or-nothing semantics ([extract], the single-entry
    /// [extract_entry_at]) return it, and the listing keeps mapping it to [ArchiveError::Fatal].
    Failed(String),
    /// The caller's cancel hook said stop (the sink's reader went away, or a write into the sink
    /// found the pipe closed): nothing is wrong with the archive.
    Cancelled,
}

impl std::fmt::Display for ArchiveError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            ArchiveError::NotSeekable(message) => write!(f, "{message}"),
            ArchiveError::Unsupported(message) => write!(f, "unsupported archive: {message}"),
            ArchiveError::Fatal(message) => write!(f, "{message}"),
            ArchiveError::NonUtf8Path => write!(f, "entry pathname is not valid UTF-8"),
            ArchiveError::LimitExceeded { entry, rule } => {
                write!(f, "limit exceeded ({rule}) at entry {entry:?}")
            }
            ArchiveError::NotFound { ordinal, path } => {
                write!(f, "no entry {path:?} at header {ordinal}")
            }
            ArchiveError::Failed(message) => write!(f, "{message}"),
            ArchiveError::Cancelled => write!(f, "cancelled"),
        }
    }
}

impl std::error::Error for ArchiveError {}

/// What [inspect] learns from one header pass over an archive.
#[derive(Debug, Clone, PartialEq)]
pub struct Inspection {
    /// The archive file's own length, from `fstat` on the descriptor.
    pub archive_bytes: u64,
    /// `archive_format() & ARCHIVE_FORMAT_BASE_MASK` after the first header: the format
    /// *family* (`0x30000` tar, `0x50000` ZIP, `0x70000` ar, `0xE0000` 7-Zip, ...; `0x60000` for
    /// an empty archive), which is what callers key decisions on.
    pub format_code: u32,
    /// `archive_format_name`, informational only: for ZIP it names the *current entry's*
    /// compression method, and it is `None` for an archive with no entries.
    pub format_name: Option<String>,
    /// The compression filters between the file and the format reader (`["gzip"]`, `["xz"]`,
    /// ...), libarchive's own always-present `"none"` filter dropped, so a plain archive is `[]`.
    pub filters: Vec<String>,
    /// `archive_read_has_encrypted_entries`: `Some(true)`/`Some(false)` when the format reader
    /// can tell (ZIP, 7-Zip, RAR), `None` when it cannot or the format has no notion of it (tar).
    pub has_encrypted_entries: Option<bool>,
    pub entries: Vec<EntryMetadata>,
    /// The policy's verdict over these entries under [Limits::structural_only]: `Some(reason)`
    /// when a rule that no destination size could relax fires -- an unsafe or duplicate path, an
    /// escaping link, an unknown size, an overflowing sum -- and `None` when only the size rules
    /// (or nothing) stand between this archive and extraction. M3.3a; M3.4 refuses extraction of
    /// anything from an archive whose structural verdict is a refusal or unknown.
    pub structural_refusal: Option<String>,
}

/// What [inspect_into] produced: the same [Inspection] as [inspect] (its `entries` are the
/// policy's input and nothing else -- the listing itself went into the sink), plus whether the
/// pass stopped short. `partial` is `Some(libarchive's message)` when a header after the first
/// entry was damaged: the sink then carries every entry read before it and a trailer flagged
/// partial, so the browser can show what was readable (M3.2 section 4's hand-off).
#[derive(Debug, Clone, PartialEq)]
pub struct ListingPass {
    pub inspection: Inspection,
    pub partial: Option<String>,
}

/// Which entries [extract] writes.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Selection {
    All,
    /// Exact entry paths, matched after the same normalisation the policy uses for duplicate
    /// detection (backslashes to slashes, trailing slashes trimmed, lower-cased), so a path taken
    /// from an [Inspection] always matches its own entry. A requested path with no entry is
    /// reported in [ExtractReport::missing], never an error.
    Paths(Vec<String>),
    /// Inclusive ranges of header ordinals ([EntryMetadata::ordinal]), `(first, last)` -- what a
    /// browsing plan selects by (M3.4). Sorted and merged before use, so overlapping or unordered
    /// ranges are fine; a range whose `first` exceeds its `last` selects nothing. The pass stops
    /// reading as soon as the highest selected ordinal has been handled, so a `tar.*` is not
    /// decompressed to its end for a member near its start.
    Ranges(Vec<(u32, u32)>),
}

/// The limits [extract] enforces while it runs -- against the bytes actually produced, not the
/// headers' claims, which is what makes them the real defence behind the policy's preflight.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ExtractLimits {
    pub max_file_bytes: u64,
    pub max_total_uncompressed_bytes: u64,
    pub max_entries: usize,
    /// [Limits::max_path_depth]/[Limits::max_name_length], for the per-entry structural re-check
    /// [extract_blocks] runs as it reaches each selected entry (M3.4).
    pub max_path_depth: usize,
    pub max_name_length: usize,
}

impl From<&Limits> for ExtractLimits {
    fn from(limits: &Limits) -> Self {
        ExtractLimits {
            max_file_bytes: limits.max_file_bytes,
            max_total_uncompressed_bytes: limits.max_total_uncompressed_bytes,
            max_entries: limits.max_entries,
            max_path_depth: limits.max_path_depth,
            max_name_length: limits.max_name_length,
        }
    }
}

impl Default for ExtractLimits {
    fn default() -> Self {
        ExtractLimits::from(&Limits::default())
    }
}

/// Where [extract] writes. The engine never creates, names or closes anything: the caller
/// (Kotlin's operation engine, through SAF) owns every destination and its lifetime.
pub trait DestinationProvider {
    /// Called once per selected entry, in archive order, for every kind but links (which are
    /// never materialised -- see [ExtractReport::skipped_links]) and `Other` (device nodes and
    /// the like, which SAF cannot create either). Return `Ok(None)` to skip it (directories, or a
    /// caller that decides not to write this one). The provider owns the fd's lifetime; the
    /// engine writes and flushes, never closes.
    fn open(&mut self, entry: &ArchiveEntry) -> Result<Option<BorrowedFd<'_>>, ArchiveError>;
    /// Called after an entry's data has been fully written and flushed to the fd `open` returned.
    fn done(&mut self, entry: &ArchiveEntry, bytes_written: u64) -> Result<(), ArchiveError>;
}

/// A non-fatal condition libarchive attached to an entry's data (M3.4): the entry is complete
/// and its bytes are what the archive holds, but `archive_read_data_block` returned
/// `ARCHIVE_WARN` for a block with a message that is not a CRC mismatch (a CRC mismatch is a
/// [FailKind::Crc] failure, never a warning). Logged by the caller, never fatal.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Warning {
    Other(String),
}

/// Why one entry is lost while the pass goes on ([BlockSink::failed]). Classified from
/// libarchive's own message: ZIP's "bad CRC" and 7-Zip's "bad CRC" are [FailKind::Crc]; ZIP's
/// "compressed/uncompressed data is wrong size" is [FailKind::Size]; any other per-entry
/// `ARCHIVE_FAILED` -- a data or header decode error -- is [FailKind::Decode]; an entry whose path
/// or link target fails the structural re-check at extraction time is [FailKind::Other].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum FailKind {
    Crc,
    Size,
    Decode,
    Other,
}

/// Where [extract_blocks] streams (M3.4): the caller owns every destination. One entry at a time,
/// in archive order: [BlockSink::begin], then for a file zero or more [BlockSink::write]s, then
/// exactly one of [BlockSink::end] or [BlockSink::failed]; a header libarchive could not parse is a
/// stand-alone [BlockSink::failed] with no `begin`. Any `Err` a method returns aborts the pass
/// with that error (an `EPIPE` on a pipe sink is [ArchiveError::Cancelled] by convention).
pub trait BlockSink {
    /// A selected entry starts. Called for every kind -- directories, links and special files
    /// included, so the sink decides what to make of them; only a file has data. `Ok(true)` to
    /// receive the entry (its `end` follows), `Ok(false)` to pass it over unread (counted in
    /// [ExtractReport::skipped]/[ExtractReport::skipped_links]).
    fn begin(&mut self, entry: &EntryMetadata) -> Result<bool, ArchiveError>;
    /// One block of the current file's data, in order; the zeros of a sparse hole come through
    /// here too, so the concatenation of the blocks is the file, byte for byte.
    fn write(&mut self, ordinal: u32, block: &[u8]) -> Result<(), ArchiveError>;
    /// The current entry is complete with `bytes` written (0 for every non-file kind).
    fn end(
        &mut self,
        ordinal: u32,
        bytes: u64,
        warning: Option<Warning>,
    ) -> Result<(), ArchiveError>;
    /// The entry at `ordinal` is lost (see [FailKind]); whatever `write`s preceded this are not to
    /// be trusted. The pass continues with the next header.
    fn failed(&mut self, ordinal: u32, kind: FailKind, message: &str) -> Result<(), ArchiveError>;
}

/// What [extract] did. On an `Err` there is no report: whatever was written before the failure
/// stays where it is, and the caller (staging, journal, recycle) owns cleanup, exactly as the
/// Kotlin `extractBounded` did -- `extract` never deletes.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct ExtractReport {
    /// Entries whose data was written and reported to [DestinationProvider::done].
    pub entries_written: usize,
    pub bytes_written: u64,
    /// Selected entries the provider declined (`Ok(None)`), plus `Other`-kind entries the engine
    /// never offered.
    pub skipped: usize,
    /// Selected symlink and hardlink entries, which the engine never offers to the provider.
    pub skipped_links: usize,
    /// `Selection::Paths` entries no archive entry matched, in the order requested.
    pub missing: Vec<String>,
    /// Selected entries lost to a per-entry failure ([BlockSink::failed]); always 0 from [extract],
    /// whose sink turns the first failure into an `Err`.
    pub entries_failed: usize,
}

/// What [extract_blocks_cancellable] hands back: the counts so far whatever happened, the error
/// if the pass did not run to the end, and the ordinal the engine blames for it.
#[derive(Debug)]
pub struct BlocksOutcome {
    pub report: ExtractReport,
    /// `Some` exactly when `result` is an `Err`: for a failure while reading an entry's data, that
    /// entry's ordinal; for a header libarchive could not read at all, or a cancel noticed between
    /// headers, the ordinal that header would have had (the count of headers read before it). A
    /// caller resuming the pass starts **after** it.
    pub stop_ordinal: Option<u32>,
    pub result: Result<(), ArchiveError>,
}

/// What [inspect_for_extraction] gathered: the archive's length and the metadata of every
/// selected entry, in archive order.
#[derive(Debug, Clone, PartialEq)]
pub struct SelectedEntries {
    pub archive_bytes: u64,
    pub entries: Vec<EntryMetadata>,
}

/// How many headers a pass reads between two calls of its cancel hook (M3.4 section 2.3 step 8):
/// a `tar.xz` header walk decompresses the whole stream, so a cancel must be noticed inside it.
pub const CANCEL_POLL_HEADERS: u32 = 64;

/// How an entry's data ended inside [Reader::stream_current_entry_data].
enum DataEnd {
    Complete {
        written: u64,
        warning: Option<Warning>,
    },
    Failed {
        kind: FailKind,
        message: String,
    },
}

/// Wraps a caller-owned raw fd as a `File` that is never closed: `ManuallyDrop` suppresses the
/// `close(2)` in `File::drop`, so the descriptor's lifetime stays entirely the caller's.
///
/// SAFETY (for the callers): `fd` must be open for the whole time the returned value is used;
/// every public function here documents that as its own contract on the caller.
fn borrow_fd(fd: RawFd) -> ManuallyDrop<File> {
    // SAFETY: see the function's own doc comment; the `ManuallyDrop` is what keeps this from
    // taking ownership (closing) the caller's descriptor.
    ManuallyDrop::new(unsafe { File::from_raw_fd(fd) })
}

/// Names a non-regular file type for [ArchiveError::NotSeekable]'s message.
fn describe_file_type(file_type: std::fs::FileType) -> &'static str {
    if file_type.is_fifo() {
        "fifo"
    } else if file_type.is_socket() {
        "socket"
    } else if file_type.is_char_device() {
        "character device"
    } else if file_type.is_block_device() {
        "block device"
    } else if file_type.is_dir() {
        "directory"
    } else {
        "unknown file type"
    }
}

/// Widens libarchive's `time_t` (`c_long`: 32-bit on armv7 bionic, 64-bit elsewhere) to the
/// `i64` [EntryMetadata::mtime] carries. A plain `as` because `i64::from` does not exist for the
/// 64-bit `c_long` (it is already `i64` there); clippy would flag the no-op on those hosts.
#[allow(clippy::unnecessary_cast)]
fn widen_time(t: sys::TimeT) -> i64 {
    t as i64
}

/// Whether `metadata` is the archive's own root directory rather than an entry in it. libarchive
/// lists the root of an ISO 9660 image as a directory named `.` (`iso9660.c`'s `build_pathname`
/// names the nameless root that way), and a tar made with `tar -C dir -cf x.tar .` carries a
/// `./` member for the same reason. It is the extraction folder itself: nothing to create,
/// nothing a user could select, and the policy's `.`-segment rule (ported verbatim from Kotlin,
/// which only ever saw ZIPs) would otherwise refuse every ISO image outright. [inspect] and
/// [extract] therefore pass over it, uncounted. Entries *under* such a root (`./file`) are left
/// exactly as libarchive names them, so the policy still judges them.
fn is_archive_root(metadata: &EntryMetadata) -> bool {
    metadata.kind == EntryKind::Directory && matches!(metadata.path.as_str(), "." | "./")
}

/// Owns a libarchive read handle for exactly one forward pass over a seekable fd -- opening it
/// twice (e.g. once for [entries] and again for [read_entry]) needs two `Reader`s, each of which
/// rewinds the descriptor to byte 0 first; this struct's `Drop` calls `archive_read_free`
/// (`archive_read_close` included). Random access within one pass is libarchive's own business
/// (the seekable ZIP reader jumps to the central directory; 7z seeks to its packs), which is why
/// the descriptor must be a regular file.
struct Reader {
    raw: *mut sys::Archive,
    /// The archive file's length from `fstat` at open (0 for a test-only unchecked pipe).
    archive_bytes: u64,
    /// How many headers [Reader::next_header] has returned so far -- the one counter behind
    /// [EntryMetadata::ordinal] for every entry point, so a listing's ordinals and
    /// [extract_entry_at]'s walk can never disagree about what index a header has.
    headers_read: u32,
}

impl Reader {
    /// The shared open path of every public function: `fstat` -> [ArchiveError::NotSeekable]
    /// unless a regular file, `lseek(fd, 0, SEEK_SET)` (see the crate doc: libarchive seeks
    /// absolutely but treats the first byte read as offset 0, so the descriptor's current offset
    /// must be 0 whatever the caller left it at), then libarchive's own open.
    fn open_fd(fd: RawFd) -> Result<Self, ArchiveError> {
        let mut file = borrow_fd(fd);
        let metadata = file
            .metadata()
            .map_err(|e| ArchiveError::Fatal(format!("fstat on the archive descriptor: {e}")))?;
        let file_type = metadata.file_type();
        if !file_type.is_file() {
            return Err(ArchiveError::NotSeekable(format!(
                "not seekable ({})",
                describe_file_type(file_type)
            )));
        }
        file.seek(SeekFrom::Start(0))
            .map_err(|e| ArchiveError::Fatal(format!("lseek to the start of the archive: {e}")))?;
        Self::open_positioned(fd, metadata.len())
    }

    /// [Reader::open_fd] without the regular-file check, and with a failed rewind ignored, so a
    /// test can feed a pipe (`std::io::pipe()`) and show what the seekable contract buys -- the
    /// M3.2 negative controls. Never reachable from the public API.
    #[cfg(test)]
    fn open_unchecked(fd: RawFd) -> Result<Self, ArchiveError> {
        let mut file = borrow_fd(fd);
        let archive_bytes = file.metadata().map(|m| m.len()).unwrap_or(0);
        let _ = file.seek(SeekFrom::Start(0));
        Self::open_positioned(fd, archive_bytes)
    }

    fn open_positioned(fd: RawFd, archive_bytes: u64) -> Result<Self, ArchiveError> {
        // SAFETY: `archive_read_new` returns either a valid, freshly allocated `*mut Archive` or
        // null on allocation failure -- the null check below is this call's own safety contract.
        let raw = unsafe { sys::archive_read_new() };
        if raw.is_null() {
            return Err(ArchiveError::Fatal("archive_read_new returned null".into()));
        }
        let reader = Reader {
            raw,
            archive_bytes,
            headers_read: 0,
        };
        // SAFETY: `raw` is a valid, just-allocated archive handle; `support_filter_all`/
        // `support_format_all` never fail in a way libarchive treats as fatal here (registering a
        // codec that is not actually compiled in is documented as harmless -- it simply cannot be
        // used later), so their return values are intentionally not checked.
        unsafe {
            sys::archive_read_support_filter_all(reader.raw);
            sys::archive_read_support_format_all(reader.raw);
        }
        // 64 KiB matches this crate's own streaming read-data buffer below and libarchive's own
        // commonly recommended default; it only affects the size of internal read()s against
        // `fd`, never correctness.
        let status = unsafe { sys::archive_read_open_fd(reader.raw, fd, 64 * 1024) };
        if let Err(error) = reader.check(status) {
            return Err(reader.classify_open_error(error));
        }
        Ok(reader)
    }

    /// Splits [ArchiveError::Unsupported] off from an open failure. libarchive runs the format
    /// bidding inside `archive_read_open_fd` (not, as one might expect, at the first
    /// `archive_read_next_header`), so "no format recognised this input" surfaces here: no bidder
    /// won (`archive_format() == 0`) and the message is `archive_read.c`'s own "Unrecognized
    /// archive format". Both are required -- a filter failing on a badly truncated stream also
    /// leaves the format at 0, and that is damage, not an unsupported format.
    fn classify_open_error(&self, error: ArchiveError) -> ArchiveError {
        let ArchiveError::Fatal(message) = error else {
            return error;
        };
        // SAFETY: `self.raw` is a valid archive handle (open failed, but the handle is live until
        // `Drop`).
        let format = unsafe { sys::archive_format(self.raw) };
        if format == 0 && message == "Unrecognized archive format" {
            return ArchiveError::Unsupported(message);
        }
        ArchiveError::Fatal(message)
    }

    /// Turns a non-OK, non-EOF, non-warning libarchive status into this crate's own error type,
    /// reading the message while `self.raw` is still valid -- a caller must never call this after
    /// the reader has already been freed. Everything is [ArchiveError::Fatal] here, `ARCHIVE_FAILED`
    /// included: the open path, the simple lookups and the listing keep M3.2's mapping.
    fn check(&self, status: c_int) -> Result<(), ArchiveError> {
        match self.check_header(status) {
            Err(ArchiveError::Failed(message)) => Err(ArchiveError::Fatal(message)),
            other => other,
        }
    }

    /// [Reader::check] with `ARCHIVE_FAILED` told apart as [ArchiveError::Failed] (M3.4): for a
    /// header status, "this header could not be parsed; the reader can still skip past it".
    /// `ARCHIVE_RETRY` (a tar header with a bad checksum) and `ARCHIVE_FATAL` stay fatal.
    fn check_header(&self, status: c_int) -> Result<(), ArchiveError> {
        if status == ARCHIVE_OK || status == ARCHIVE_EOF || status == ARCHIVE_WARN {
            return Ok(());
        }
        if status == ARCHIVE_FAILED {
            return Err(ArchiveError::Failed(self.error_message(status)));
        }
        Err(ArchiveError::Fatal(self.error_message(status)))
    }

    /// The data-status twin of [Reader::check_header]: for a data block, `ARCHIVE_FAILED` is "this
    /// entry's data is wrong (a CRC or size mismatch at its end); the archive goes on".
    fn check_data(&self, status: c_int) -> Result<(), ArchiveError> {
        self.check_header(status)
    }

    fn error_message(&self, status: c_int) -> String {
        // SAFETY: `self.raw` is non-null and owned by this `Reader` for its whole lifetime.
        unsafe {
            let ptr = sys::archive_error_string(self.raw);
            if ptr.is_null() {
                format!("libarchive error {status}")
            } else {
                CStr::from_ptr(ptr).to_string_lossy().into_owned()
            }
        }
    }

    /// The names of the filters libarchive put between `fd` and the format reader. Final as soon
    /// as [Reader::open_fd] has returned: `archive_read_open_fd` runs both the filter and the
    /// format bidding before it returns.
    fn filter_names(&self) -> Vec<String> {
        // SAFETY: `self.raw` is a valid, open archive handle; `archive_filter_name` returns null
        // or a pointer into storage libarchive owns for as long as the handle lives, which this
        // `Reader` does for the whole of this call.
        unsafe {
            let count = sys::archive_filter_count(self.raw);
            (0..count)
                .map(|n| {
                    let ptr = sys::archive_filter_name(self.raw, n);
                    if ptr.is_null() {
                        "(unnamed)".to_string()
                    } else {
                        CStr::from_ptr(ptr).to_string_lossy().into_owned()
                    }
                })
                .collect()
        }
    }

    /// `archive_format() & ARCHIVE_FORMAT_BASE_MASK`: the format family, meaningful once the
    /// first header (or EOF) has been read.
    fn format_code(&self) -> u32 {
        // SAFETY: `self.raw` is a valid, open archive handle.
        let format = unsafe { sys::archive_format(self.raw) };
        (format & ARCHIVE_FORMAT_BASE_MASK) as u32
    }

    fn format_name(&self) -> Option<String> {
        // SAFETY: `self.raw` is valid and open; the returned pointer is null or into storage
        // libarchive owns for as long as the handle lives.
        unsafe {
            let ptr = sys::archive_format_name(self.raw);
            if ptr.is_null() {
                None
            } else {
                Some(CStr::from_ptr(ptr).to_string_lossy().into_owned())
            }
        }
    }

    /// `archive_read_has_encrypted_entries`, asked after the header pass so a format reader that
    /// learns it per entry (ZIP) has seen them all: `Some` for a definite yes/no, `None` for
    /// `ARCHIVE_READ_FORMAT_ENCRYPTION_UNSUPPORTED`/`_DONT_KNOW`.
    fn has_encrypted_entries(&self) -> Option<bool> {
        // SAFETY: `self.raw` is a valid, open archive handle.
        match unsafe { sys::archive_read_has_encrypted_entries(self.raw) } {
            n if n > 0 => Some(true),
            0 => Some(false),
            _ => None,
        }
    }

    /// Advances to the next entry's header, returning `None` at end of archive and otherwise a
    /// pointer libarchive owns, valid until the next call on this reader. Per libarchive's own
    /// documented contract, calling this again before draining a prior entry's data silently
    /// skips whatever of that entry's body was never read -- exactly what [entries] and
    /// [inspect] rely on to list every entry without reading any data, and what [extract] relies
    /// on to pass over unselected entries.
    fn next_header(&mut self) -> Result<Option<*mut sys::ArchiveEntry>, ArchiveError> {
        match self.next_header_raw() {
            Err(ArchiveError::Failed(message)) => Err(ArchiveError::Fatal(message)),
            other => other,
        }
    }

    /// [Reader::next_header] with a header libarchive could not parse reported as
    /// [ArchiveError::Failed] instead of fatal (M3.4). Such a header **counts**: libarchive has
    /// consumed it (`ARCHIVE_STATE_DATA_RECOVERY`, its body is skipped on the next call), so it
    /// occupies an ordinal exactly as it does in a listing that reached it, and
    /// [Reader::current_ordinal] names it after this returns. Its data must never be read.
    fn next_header_raw(&mut self) -> Result<Option<*mut sys::ArchiveEntry>, ArchiveError> {
        let mut entry_ptr: *mut sys::ArchiveEntry = std::ptr::null_mut();
        // SAFETY: `self.raw` is a valid, open archive handle; `entry_ptr` is an out-parameter
        // libarchive sets to point at internally-owned storage that stays valid until the next
        // `archive_read_next_header`/`archive_read_free` call on this same `self.raw`.
        let status = unsafe { sys::archive_read_next_header(self.raw, &mut entry_ptr) };
        if status == ARCHIVE_EOF {
            return Ok(None);
        }
        match self.check_header(status) {
            Ok(()) => {}
            Err(ArchiveError::Failed(message)) => {
                self.count_header()?;
                return Err(ArchiveError::Failed(message));
            }
            Err(error) => return Err(self.classify_header_error(error)),
        }
        if entry_ptr.is_null() {
            return Err(ArchiveError::Fatal(
                "archive_read_next_header reported success with a null entry".into(),
            ));
        }
        self.count_header()?;
        Ok(Some(entry_ptr))
    }

    fn count_header(&mut self) -> Result<(), ArchiveError> {
        self.headers_read = self.headers_read.checked_add(1).ok_or_else(|| {
            ArchiveError::Fatal("more than u32::MAX headers in one archive".into())
        })?;
        Ok(())
    }

    /// The ordinal of the header [Reader::next_header] most recently returned: its 0-based index
    /// among every header read on this reader.
    fn current_ordinal(&self) -> u32 {
        self.headers_read.saturating_sub(1)
    }

    /// Splits [ArchiveError::Unsupported] off from a header-read failure: a 7-Zip archive whose
    /// header itself is encrypted (`7zip.c`: "The %s is encrypted, but currently not supported",
    /// raised while reading the first header, after the reader has set its format). Everything
    /// else stays `Fatal` -- an unrecognised format never gets this far, see
    /// [Reader::classify_open_error].
    fn classify_header_error(&self, error: ArchiveError) -> ArchiveError {
        let ArchiveError::Fatal(message) = error else {
            return error;
        };
        // SAFETY: `self.raw` is a valid, open archive handle.
        let format = unsafe { sys::archive_format(self.raw) };
        if format & ARCHIVE_FORMAT_BASE_MASK == ARCHIVE_FORMAT_7ZIP && message.contains("encrypted")
        {
            return ArchiveError::Unsupported(message);
        }
        ArchiveError::Fatal(message)
    }

    /// The raw bytes of the current entry's pathname, exactly as stored (libarchive passes
    /// non-UTF-8 names through untouched off Windows).
    ///
    /// SAFETY (for callers): `entry` must be the pointer the most recent [Reader::next_header]
    /// returned, on a reader that has not been advanced since.
    unsafe fn pathname_bytes<'a>(entry: *mut sys::ArchiveEntry) -> Result<&'a [u8], ArchiveError> {
        // SAFETY: per this function's own contract, `entry` is libarchive-owned and valid; the
        // pathname pointer is null or a NUL-terminated string owned by the same entry.
        let ptr = unsafe { sys::archive_entry_pathname(entry) };
        if ptr.is_null() {
            return Err(ArchiveError::Fatal("archive entry has no pathname".into()));
        }
        Ok(unsafe { CStr::from_ptr(ptr) }.to_bytes())
    }

    /// The simple listing shape of the current entry, failing with [ArchiveError::NonUtf8Path]
    /// on a name that is not UTF-8 (see that variant for why the lookups keep this strictness).
    ///
    /// SAFETY (for callers): as [Reader::pathname_bytes].
    unsafe fn listing_entry(entry: *mut sys::ArchiveEntry) -> Result<ArchiveEntry, ArchiveError> {
        // SAFETY: forwarded from this function's own contract.
        let path = std::str::from_utf8(unsafe { Self::pathname_bytes(entry) }?)
            .map_err(|_| ArchiveError::NonUtf8Path)?
            .to_string();
        // SAFETY: same `entry` validity as above.
        let (size, filetype) = unsafe {
            (
                sys::archive_entry_size(entry),
                sys::archive_entry_filetype(entry),
            )
        };
        Ok(ArchiveEntry {
            path,
            size,
            is_directory: filetype & AE_IFMT == AE_IFDIR,
        })
    }

    /// The full [EntryMetadata] of the current entry, its `ordinal` being this reader's count of
    /// headers read. Never fails on a name: a non-UTF-8 one is decoded lossily and flagged.
    /// Hardlinks are detected from `archive_entry_hardlink` **before** the file type is
    /// consulted, because libarchive reports a hardlink as `AE_IFREG`.
    ///
    /// SAFETY (for callers): as [Reader::pathname_bytes].
    unsafe fn metadata(
        &self,
        entry: *mut sys::ArchiveEntry,
    ) -> Result<EntryMetadata, ArchiveError> {
        // SAFETY: forwarded from this function's own contract.
        let raw_name = unsafe { Self::pathname_bytes(entry) }?;
        let (path, name_lossy) = match std::str::from_utf8(raw_name) {
            Ok(name) => (name.to_string(), false),
            Err(_) => (String::from_utf8_lossy(raw_name).into_owned(), true),
        };
        // SAFETY: `entry` is valid per the contract; every accessor below reads a field of the
        // entry libarchive owns, and the two string accessors return null or a NUL-terminated
        // string owned by the same entry, copied out before this function returns.
        unsafe {
            let lossy = |ptr: *const std::os::raw::c_char| -> Option<String> {
                if ptr.is_null() {
                    None
                } else {
                    Some(CStr::from_ptr(ptr).to_string_lossy().into_owned())
                }
            };
            let hardlink = lossy(sys::archive_entry_hardlink(entry));
            let (kind, link_target) = if hardlink.is_some() {
                (EntryKind::Hardlink, hardlink)
            } else {
                match sys::archive_entry_filetype(entry) & AE_IFMT {
                    AE_IFDIR => (EntryKind::Directory, None),
                    AE_IFREG => (EntryKind::File, None),
                    AE_IFLNK => (EntryKind::Symlink, lossy(sys::archive_entry_symlink(entry))),
                    _ => (EntryKind::Other, None),
                }
            };
            let uncompressed = if sys::archive_entry_size_is_set(entry) != 0 {
                u64::try_from(sys::archive_entry_size(entry)).ok()
            } else {
                None
            };
            let mtime = if sys::archive_entry_mtime_is_set(entry) != 0 {
                Some(widen_time(sys::archive_entry_mtime(entry)))
            } else {
                None
            };
            Ok(EntryMetadata {
                ordinal: self.current_ordinal(),
                path,
                name_lossy,
                kind,
                link_target,
                uncompressed,
                compressed: None,
                mtime,
                mode: sys::archive_entry_perm(entry),
                encrypted_data: sys::archive_entry_is_data_encrypted(entry) != 0,
                encrypted_metadata: sys::archive_entry_is_metadata_encrypted(entry) != 0,
            })
        }
    }

    /// Advances to the next entry as an [ArchiveEntry], for the simple listing and the lookups.
    fn next_entry(&mut self) -> Result<Option<ArchiveEntry>, ArchiveError> {
        match self.next_header()? {
            // SAFETY: `entry` was just returned by `next_header` on this reader.
            Some(entry) => Ok(Some(unsafe { Self::listing_entry(entry) }?)),
            None => Ok(None),
        }
    }

    /// Reads the CURRENT entry's (the one [Reader::next_header] most recently returned) full body.
    /// Must be called at most once per entry, before the next [Reader::next_header] call.
    fn read_current_entry_data(&mut self) -> Result<Vec<u8>, ArchiveError> {
        let mut data = Vec::new();
        let mut buf = [0u8; 64 * 1024];
        loop {
            // SAFETY: `self.raw` is valid and open; `buf` is a plain stack array and
            // `archive_read_data` writes at most `buf.len()` bytes into it, matching the `len`
            // argument passed.
            let read = unsafe {
                sys::archive_read_data(self.raw, buf.as_mut_ptr() as *mut c_void, buf.len())
            };
            if read < 0 {
                self.check(read as c_int)?;
                // `check` only returns `Ok(())` for OK/EOF/WARN, none of which a negative `read`
                // is, so this is unreachable in practice; kept as a safety net over `unreachable!()`.
                return Err(ArchiveError::Fatal(format!(
                    "archive_read_data returned {read} without a matching error status"
                )));
            }
            if read == 0 {
                return Ok(data);
            }
            data.extend_from_slice(&buf[..read as usize]);
        }
    }

    /// Streams the CURRENT entry's body to `out` block by block (`archive_read_data_block`, zero
    /// copy out of libarchive's own buffers), enforcing `limits` against the bytes actually
    /// produced *before* each block is handed over, so nothing past a cap ever reaches `out`. Holes
    /// in a sparse entry (a block whose offset is past what has been written, or a final EOF
    /// offset past it) are handed over as zeros, so the output is byte-exact and sized as the entry
    /// declares. `running_total` accumulates across entries for the total cap.
    ///
    /// The entry's own failures come back as [DataEnd::Failed], never an `Err` (M3.4): libarchive
    /// returns `ARCHIVE_FAILED` for a ZIP CRC or size mismatch **after** the data, and
    /// `ARCHIVE_WARN` with the final block for a 7-Zip CRC mismatch (the block is withheld) -- the
    /// entry is lost, the archive is fine. An `ARCHIVE_WARN` that is not a CRC mismatch keeps the
    /// block and is reported as [Warning::Other]. Everything else negative (a decode error, a
    /// truncated body: the archive is dead) is `Err(Fatal)`; a cap is `Err(LimitExceeded)`; an
    /// error from `out` is returned as `out` made it.
    fn stream_current_entry_data(
        &mut self,
        out: &mut dyn FnMut(&[u8]) -> Result<(), ArchiveError>,
        entry: &EntryMetadata,
        limits: &ExtractLimits,
        running_total: &mut u64,
    ) -> Result<DataEnd, ArchiveError> {
        // The per-entry cap: the limit, or the entry's own declared size if that is smaller --
        // data past what the header declared is a header that lied.
        let declared = entry.uncompressed;
        let cap = declared.map_or(limits.max_file_bytes, |d| d.min(limits.max_file_bytes));
        let mut written: u64 = 0;
        let mut warning: Option<Warning> = None;

        // Accounts `more` bytes about to be produced for this entry against every cap, naming
        // the rule that stops it.
        let mut account = |written: u64, more: u64| -> Result<(), ArchiveError> {
            let next = written.saturating_add(more);
            if next > cap {
                let rule = if declared.is_some_and(|d| next > d) {
                    "declared"
                } else {
                    "file"
                };
                return Err(ArchiveError::LimitExceeded {
                    entry: entry.path.clone(),
                    rule,
                });
            }
            let total = running_total.saturating_add(more);
            if total > limits.max_total_uncompressed_bytes {
                return Err(ArchiveError::LimitExceeded {
                    entry: entry.path.clone(),
                    rule: "total",
                });
            }
            *running_total = total;
            Ok(())
        };

        loop {
            let mut buff: *const c_void = std::ptr::null();
            let mut size: usize = 0;
            let mut offset: sys::LaInt64T = 0;
            // SAFETY: `self.raw` is valid, open and positioned in an entry's data; the three
            // out-parameters are plain locals libarchive fills in, and `buff` then points into
            // storage libarchive owns until the next read call on this same handle -- the slice
            // built from it below is consumed (handed to `out`) before any such call.
            let status = unsafe {
                sys::archive_read_data_block(self.raw, &mut buff, &mut size, &mut offset)
            };
            let offset = u64::try_from(offset).map_err(|_| {
                ArchiveError::Fatal(format!(
                    "negative data offset {offset} in entry {:?}",
                    entry.path
                ))
            })?;
            if status == ARCHIVE_EOF {
                // A trailing hole in a sparse entry: the EOF block's offset is the entry's full
                // size (tar reports `disk_size`), so extend with zeros up to it.
                if offset > written {
                    account(written, offset - written)?;
                    write_zeros(out, offset - written)?;
                    written = offset;
                }
                break;
            }
            if status == ARCHIVE_FAILED {
                let message = self.error_message(status);
                return Ok(DataEnd::Failed {
                    kind: classify_data_failure(&message),
                    message,
                });
            }
            let block_warning = if status == ARCHIVE_WARN {
                let message = self.error_message(status);
                if is_crc_message(&message) {
                    return Ok(DataEnd::Failed {
                        kind: FailKind::Crc,
                        message,
                    });
                }
                Some(message)
            } else {
                None
            };
            self.check_data(status)?;
            if offset < written {
                return Err(ArchiveError::Fatal(format!(
                    "data blocks out of order in entry {:?} (offset {offset} after {written} bytes)",
                    entry.path
                )));
            }
            if offset > written {
                account(written, offset - written)?;
                write_zeros(out, offset - written)?;
                written = offset;
            }
            if size > 0 {
                account(written, size as u64)?;
                // SAFETY: `archive_read_data_block` returned OK/WARN with `size > 0`, so `buff`
                // points at `size` readable bytes libarchive owns until the next read call.
                let block = unsafe { std::slice::from_raw_parts(buff as *const u8, size) };
                out(block)?;
                written += size as u64;
            }
            if let Some(message) = block_warning {
                warning = Some(Warning::Other(message));
            }
        }
        Ok(DataEnd::Complete { written, warning })
    }
}

/// libarchive's message for a data-level `ARCHIVE_FAILED`, classified: ZIP's "ZIP bad CRC" (and
/// 7-Zip's "7-Zip bad CRC", which arrives as a warning) name a CRC mismatch; ZIP's "compressed
/// data is wrong size"/"uncompressed data is wrong size" a size mismatch; anything else is a
/// decode failure of that entry.
fn classify_data_failure(message: &str) -> FailKind {
    if is_crc_message(message) {
        FailKind::Crc
    } else if message.contains("wrong size") {
        FailKind::Size
    } else {
        FailKind::Decode
    }
}

fn is_crc_message(message: &str) -> bool {
    message.contains("CRC")
}

fn write_error(path: &str, error: std::io::Error) -> ArchiveError {
    ArchiveError::Fatal(format!("writing the destination for {path:?}: {error}"))
}

/// Hands `count` zero bytes to `out` in bounded chunks (a sparse hole made explicit).
fn write_zeros(
    out: &mut dyn FnMut(&[u8]) -> Result<(), ArchiveError>,
    mut count: u64,
) -> Result<(), ArchiveError> {
    static ZEROS: [u8; 64 * 1024] = [0u8; 64 * 1024];
    while count > 0 {
        let chunk = usize::try_from(count.min(ZEROS.len() as u64)).unwrap_or(ZEROS.len());
        out(&ZEROS[..chunk])?;
        count -= chunk as u64;
    }
    Ok(())
}

impl Drop for Reader {
    fn drop(&mut self) {
        // SAFETY: `self.raw` was allocated by `archive_read_new` in `Reader::open_positioned` and
        // is never freed anywhere else; `Reader` has no `Clone`, so this runs at most once per
        // handle.
        unsafe {
            sys::archive_read_free(self.raw);
        }
    }
}

/// Lists every entry in the archive at `fd`, without reading any entry's data. `fd` must be a
/// regular file (see the crate doc); it is rewound to byte 0 first and left wherever libarchive
/// stopped. Fails with [ArchiveError::NonUtf8Path] on a name that is not UTF-8 -- [inspect] is the
/// listing that never does.
pub fn entries(fd: RawFd) -> Result<Vec<ArchiveEntry>, ArchiveError> {
    let mut reader = Reader::open_fd(fd)?;
    let mut result = Vec::new();
    while let Some(entry) = reader.next_entry()? {
        result.push(entry);
    }
    Ok(result)
}

/// Reads one entry's full data by path, scanning forward from byte 0 of `fd` (a regular file, see
/// the crate doc). Returns `Ok(None)` if no entry with exactly this path exists -- a normal,
/// expected outcome, not an error. Callers that only need "does this path exist" without its data
/// should use [entries] instead: this function pays for a full read of every entry's body up to
/// and including the match. For a bounded write to a destination, use [extract].
pub fn read_entry(fd: RawFd, path: &str) -> Result<Option<Vec<u8>>, ArchiveError> {
    read_entry_from(Reader::open_fd(fd)?, path)
}

/// [read_entry] over an already-open [Reader] -- split out so a test can drive the same lookup
/// through [Reader::open_unchecked] on a pipe (the M3.2 negative controls).
fn read_entry_from(mut reader: Reader, path: &str) -> Result<Option<Vec<u8>>, ArchiveError> {
    while let Some(entry) = reader.next_entry()? {
        if entry.path == path {
            return Ok(Some(reader.read_current_entry_data()?));
        }
    }
    Ok(None)
}

/// Names the compression filters libarchive chose for the archive at `fd` (a regular file, see
/// the crate doc), the one feeding the format reader first (e.g. `"lz4"`) and libarchive's own
/// `"none"` filter (raw I/O against `fd`) last, so an uncompressed archive is just `["none"]`. A
/// codec libarchive was built without still bids, but by shelling out to an external program, and
/// then names itself `"Program: <command>"` -- which is what lets a test prove a backend really is
/// compiled in rather than merely tolerated. [Inspection::filters] is the same list without
/// `"none"`.
pub fn filter_names(fd: RawFd) -> Result<Vec<String>, ArchiveError> {
    let reader = Reader::open_fd(fd)?;
    Ok(reader.filter_names())
}

/// One forward header pass over the archive at `fd` (a regular file, see the crate doc), never
/// reading any entry's data: every entry's [EntryMetadata], the format family, the filter chain
/// and the encryption verdict. Uses only [Limits::max_listing_entries] of `limits` -- past it the
/// result is `LimitExceeded { entry, rule: "listing" }`, a memory bound for the decoder process,
/// not a policy verdict ([inspect_with_policy] gives that). Non-UTF-8 names are decoded lossily
/// and flagged, never an error. The archive's own root directory, when a format lists one
/// ([is_archive_root]), is not an entry.
pub fn inspect(fd: RawFd, limits: &Limits) -> Result<Inspection, ArchiveError> {
    inspect_reader(Reader::open_fd(fd)?, limits)
}

/// [inspect]'s header pass over an already-open [Reader] -- split out so a test can run the same
/// pass through [Reader::open_unchecked] on a pipe and show what the streaming readers cannot
/// report (the M3.2 negative controls).
fn inspect_reader(reader: Reader, limits: &Limits) -> Result<Inspection, ArchiveError> {
    header_pass(reader, limits, None).map(|pass| pass.inspection)
}

/// [inspect] with the [listing] codec attached (M3.3): each header is encoded and written to
/// `sink` **as it is read**, so the bytes flow during the pass and the only copy of the table
/// kept in this process is the `Vec<EntryMetadata>` the policy needs. Two behaviours differ from
/// [inspect], both because a browser wants what was readable rather than nothing: a damaged
/// header after at least one entry ends the pass with the trailer flagged partial and
/// `Ok(ListingPass { partial: Some(message) })` instead of `Err(Fatal)`; and the sink receives no
/// trailer at all when the pass fails outright (an unrecognised format, damage before the first
/// entry, the listing bound), which the Kotlin reader treats as corrupt -- the caller sees the
/// `Err` first anyway. `sink` is caller-owned and never closed here.
pub fn inspect_into(
    fd: RawFd,
    limits: &Limits,
    sink: &mut dyn Write,
) -> Result<ListingPass, ArchiveError> {
    header_pass(Reader::open_fd(fd)?, limits, Some(sink))
}

/// The one header pass behind [inspect] and [inspect_into]. Ordinals come from the [Reader]'s own
/// header count ([EntryMetadata::ordinal]): every `archive_read_next_header` call counts, the
/// archive's own root directory included (it is skipped as an entry but occupies its index), so
/// [extract_entry_at]'s walk needs no knowledge of what the listing dropped.
fn header_pass(
    mut reader: Reader,
    limits: &Limits,
    sink: Option<&mut dyn Write>,
) -> Result<ListingPass, ArchiveError> {
    let mut writer = match sink {
        Some(sink) => Some(
            listing::ListingWriter::new(sink)
                .map_err(|e| ArchiveError::Fatal(format!("writing the listing: {e}")))?,
        ),
        None => None,
    };
    let mut entries = Vec::new();
    let mut format: Option<(u32, Option<String>)> = None;
    let mut partial: Option<String> = None;
    loop {
        let next = match reader.next_header() {
            Ok(next) => next,
            // Damage after at least one entry, on the listing path only: keep what was read.
            Err(ArchiveError::Fatal(message)) if writer.is_some() && !entries.is_empty() => {
                partial = Some(message);
                None
            }
            Err(error) => return Err(error),
        };
        if format.is_none() {
            // After the first header, or EOF for an empty archive (`ARCHIVE_FORMAT_EMPTY`).
            format = Some((reader.format_code(), reader.format_name()));
        }
        let Some(entry) = next else {
            break;
        };
        // SAFETY: `entry` was just returned by `next_header` on this reader.
        let metadata = unsafe { reader.metadata(entry) }?;
        if is_archive_root(&metadata) {
            continue;
        }
        if entries.len() >= limits.max_listing_entries {
            return Err(ArchiveError::LimitExceeded {
                entry: metadata.path,
                rule: "listing",
            });
        }
        if let Some(writer) = writer.as_mut() {
            writer
                .record(&metadata)
                .map_err(|e| ArchiveError::Fatal(format!("writing the listing: {e}")))?;
        }
        entries.push(metadata);
    }
    if let Some(writer) = writer {
        writer
            .finish(partial.is_some())
            .map_err(|e| ArchiveError::Fatal(format!("writing the listing: {e}")))?;
    }
    let (format_code, format_name) = format.unwrap_or((0, None));
    let structural_refusal =
        policy::evaluate(reader.archive_bytes, &entries, &limits.structural_only())
            .reason
            .map(str::to_string);
    Ok(ListingPass {
        inspection: Inspection {
            archive_bytes: reader.archive_bytes,
            format_code,
            format_name,
            filters: reader
                .filter_names()
                .into_iter()
                .filter(|name| name != "none")
                .collect(),
            has_encrypted_entries: reader.has_encrypted_entries(),
            entries,
            structural_refusal,
        },
        partial,
    })
}

/// [inspect], then the extraction [policy] over what it found: `evaluate(archive_bytes,
/// &entries, limits)`. The `Inspection` is returned alongside the verdict so a caller never
/// inspects twice.
pub fn inspect_with_policy(
    fd: RawFd,
    limits: &Limits,
) -> Result<(Inspection, Decision), ArchiveError> {
    let inspection = inspect(fd, limits)?;
    let decision = policy::evaluate(inspection.archive_bytes, &inspection.entries, limits);
    Ok((inspection, decision))
}

/// Streams the selected entries of the archive at `fd` (a regular file, see the crate doc) into
/// descriptors `dest` supplies, one forward pass, enforcing `limits` against the bytes actually
/// produced: an entry whose data exceeds [ExtractLimits::max_file_bytes] or its own declared
/// size, a running total past [ExtractLimits::max_total_uncompressed_bytes], or more than
/// [ExtractLimits::max_entries] selected entries stops the whole extraction with
/// [ArchiveError::LimitExceeded] naming the entry and the rule. Whatever was written before a
/// failure stays: the caller owns cleanup, and this function never deletes.
///
/// Symlinks and hardlinks are never materialised (SAF cannot create them) -- they are counted in
/// [ExtractReport::skipped_links] and `dest` is not consulted; `Other`-kind entries (device
/// nodes, fifos) likewise go uncounted in [ExtractReport::skipped]. Entries not selected are
/// passed over without reading their data. Names that are not UTF-8 are decoded lossily, the same
/// way [inspect] reports them, so a path taken from an [Inspection] matches its entry here; the
/// archive's own root directory ([is_archive_root]) is passed over uncounted, as [inspect] omits it.
///
/// Since M3.4 an adapter over [extract_blocks] with part 3's all-or-nothing semantics kept: a
/// per-entry failure (a CRC or size mismatch, a header libarchive could not parse) is
/// `Err(`[ArchiveError::Failed]`)` here, where [extract_blocks] would report it and go on.
pub fn extract(
    fd: RawFd,
    selection: &Selection,
    limits: &ExtractLimits,
    dest: &mut dyn DestinationProvider,
) -> Result<ExtractReport, ArchiveError> {
    let mut reader = Reader::open_fd(fd)?;
    let mut sink = ProviderSink { dest, open: None };
    let outcome = run_blocks(&mut reader, selection, limits, &mut sink, &mut || false);
    outcome.result?;
    Ok(outcome.report)
}

/// [extract]'s [BlockSink]: offers files and directories to the [DestinationProvider], declines
/// links and special files on its behalf, writes into the descriptor the provider returned, and
/// turns the first per-entry failure into an error.
struct ProviderSink<'a> {
    dest: &'a mut dyn DestinationProvider,
    /// The entry being written and the provider's descriptor for it (never closed here).
    open: Option<(ArchiveEntry, ManuallyDrop<File>)>,
}

impl BlockSink for ProviderSink<'_> {
    fn begin(&mut self, entry: &EntryMetadata) -> Result<bool, ArchiveError> {
        match entry.kind {
            EntryKind::Symlink | EntryKind::Hardlink | EntryKind::Other => return Ok(false),
            EntryKind::File | EntryKind::Directory => {}
        }
        let listing = ArchiveEntry::from_metadata(entry);
        let fd = match self.dest.open(&listing)? {
            None => return Ok(false),
            // The provider owns this descriptor: written to and flushed, never closed.
            Some(out_fd) => out_fd.as_raw_fd(),
        };
        self.open = Some((listing, borrow_fd(fd)));
        Ok(true)
    }

    fn write(&mut self, _ordinal: u32, block: &[u8]) -> Result<(), ArchiveError> {
        let (listing, out) = self
            .open
            .as_mut()
            .ok_or_else(|| ArchiveError::Fatal("data block outside an entry".into()))?;
        out.write_all(block)
            .map_err(|e| write_error(&listing.path, e))
    }

    fn end(
        &mut self,
        _ordinal: u32,
        bytes: u64,
        _warning: Option<Warning>,
    ) -> Result<(), ArchiveError> {
        let (listing, mut out) = self
            .open
            .take()
            .ok_or_else(|| ArchiveError::Fatal("entry end outside an entry".into()))?;
        out.flush().map_err(|e| write_error(&listing.path, e))?;
        self.dest.done(&listing, bytes)
    }

    fn failed(
        &mut self,
        _ordinal: u32,
        _kind: FailKind,
        message: &str,
    ) -> Result<(), ArchiveError> {
        self.open = None;
        Err(ArchiveError::Failed(message.to_string()))
    }
}

/// Streams the data of the one entry at header `ordinal` of the archive at `fd` (a regular file,
/// see the crate doc) into `dest_fd` (caller-owned; written and flushed, never closed), and
/// returns the bytes written. Walks the headers -- `archive_read_next_header` skips bodies, so on
/// a seekable ZIP this is a central-directory walk and on a compressed tar it decompresses up to
/// the entry -- checks that the header's path is byte-for-byte `expected_path` (the string the
/// listing carried for it; see [listing]), streams that entry under `limits`, and **returns
/// without reading further**: the [Reader] is dropped right after the entry, so a 1,000-member
/// tarball is not walked to its end for its first member. No header at `ordinal`, or a different
/// path there, is [ArchiveError::NotFound]. Whatever kind the header has is streamed as its data
/// (a directory or link has none, so zero bytes come out); refusing links and directories is the
/// caller's decision, made before any byte moves. Since M3.4 the one-range case of
/// [extract_blocks]; a per-entry failure of that one entry (a CRC mismatch) is
/// `Err(`[ArchiveError::Failed]`)`.
pub fn extract_entry_at(
    fd: RawFd,
    ordinal: usize,
    expected_path: &str,
    limits: &ExtractLimits,
    dest_fd: RawFd,
) -> Result<u64, ArchiveError> {
    let not_found = || ArchiveError::NotFound {
        ordinal,
        path: expected_path.to_string(),
    };
    let Ok(wanted) = u32::try_from(ordinal) else {
        return Err(not_found());
    };
    let mut reader = Reader::open_fd(fd)?;
    let mut sink = EntrySink {
        expected_path,
        ordinal,
        // The caller owns this descriptor: written to and flushed, never closed.
        out: borrow_fd(dest_fd),
        written: None,
    };
    // The single-entry cap: the whole budget is this one entry's.
    let outcome = run_blocks(
        &mut reader,
        &Selection::Ranges(vec![(wanted, wanted)]),
        limits,
        &mut sink,
        &mut || false,
    );
    outcome.result?;
    sink.written.ok_or_else(not_found)
}

/// [extract_entry_at]'s [BlockSink]: the path check, one destination, every kind accepted.
struct EntrySink<'a> {
    expected_path: &'a str,
    ordinal: usize,
    out: ManuallyDrop<File>,
    written: Option<u64>,
}

impl BlockSink for EntrySink<'_> {
    fn begin(&mut self, entry: &EntryMetadata) -> Result<bool, ArchiveError> {
        if entry.path != self.expected_path {
            return Err(ArchiveError::NotFound {
                ordinal: self.ordinal,
                path: self.expected_path.to_string(),
            });
        }
        Ok(true)
    }

    fn write(&mut self, _ordinal: u32, block: &[u8]) -> Result<(), ArchiveError> {
        self.out
            .write_all(block)
            .map_err(|e| write_error(self.expected_path, e))
    }

    fn end(
        &mut self,
        _ordinal: u32,
        bytes: u64,
        _warning: Option<Warning>,
    ) -> Result<(), ArchiveError> {
        self.out
            .flush()
            .map_err(|e| write_error(self.expected_path, e))?;
        self.written = Some(bytes);
        Ok(())
    }

    fn failed(
        &mut self,
        _ordinal: u32,
        _kind: FailKind,
        message: &str,
    ) -> Result<(), ArchiveError> {
        Err(ArchiveError::Failed(message.to_string()))
    }
}

/// The M3.4 bulk path: one forward pass over the archive at `fd` (a regular file, see the crate
/// doc) streaming every selected entry through `sink` (design section 2.5). Per selected entry:
/// [BlockSink::begin], then -- for an entry the sink accepted -- the structural rules re-checked
/// ([policy::structural_check]; a failing entry is [BlockSink::failed] with [FailKind::Other] and
/// its data is never read), the data for a file under
/// `limits` (a cap aborts the pass with [ArchiveError::LimitExceeded], as [extract] does), then
/// [BlockSink::end] -- or [BlockSink::failed] when libarchive reports the entry's data wrong (a
/// CRC or size mismatch, a decode error: `ARCHIVE_FAILED`/a CRC `ARCHIVE_WARN`), after which the
/// pass **continues** with the next header. A header libarchive cannot parse (`ARCHIVE_FAILED`
/// from `archive_read_next_header`) counts its ordinal, is [BlockSink::failed] with
/// [FailKind::Decode] when selected, has no data read (reading it would turn the archive fatal),
/// and the pass continues; the collateral loss libarchive causes on a solid 7-Zip boundary is
/// accepted. `ARCHIVE_FATAL` (a decode error inside a solid folder, a truncated body, a bad tar
/// checksum) ends the pass with `Err(Fatal)`. The pass stops reading once the highest ordinal a
/// [Selection::Ranges] names has been handled. Whatever the sink wrote stays: the caller owns
/// cleanup.
pub fn extract_blocks(
    fd: RawFd,
    selection: &Selection,
    limits: &ExtractLimits,
    sink: &mut dyn BlockSink,
) -> Result<ExtractReport, ArchiveError> {
    let outcome = extract_blocks_cancellable(fd, selection, limits, sink, &mut || false);
    outcome.result?;
    Ok(outcome.report)
}

/// [extract_blocks] with a cancel hook, called every [CANCEL_POLL_HEADERS] headers (the sink's
/// reader hanging up, in the decoder process), and the counts kept on failure: the report so far,
/// the error, and the ordinal to resume after ([BlocksOutcome::stop_ordinal]). `cancel` returning
/// `true` ends the pass with [ArchiveError::Cancelled].
pub fn extract_blocks_cancellable(
    fd: RawFd,
    selection: &Selection,
    limits: &ExtractLimits,
    sink: &mut dyn BlockSink,
    cancel: &mut dyn FnMut() -> bool,
) -> BlocksOutcome {
    let mut reader = match Reader::open_fd(fd) {
        Ok(reader) => reader,
        Err(error) => {
            return BlocksOutcome {
                report: ExtractReport::default(),
                stop_ordinal: None,
                result: Err(error),
            }
        }
    };
    run_blocks(&mut reader, selection, limits, sink, cancel)
}

/// The loop behind [extract], [extract_entry_at] and [extract_blocks].
fn run_blocks(
    reader: &mut Reader,
    selection: &Selection,
    limits: &ExtractLimits,
    sink: &mut dyn BlockSink,
    cancel: &mut dyn FnMut() -> bool,
) -> BlocksOutcome {
    let mut matcher = Matcher::new(selection);
    let mut report = ExtractReport::default();
    // The ordinal the engine is at: the header just read, or the one about to be read.
    let mut at: u32 = 0;
    let result = run_blocks_loop(
        reader,
        &mut matcher,
        limits,
        sink,
        cancel,
        &mut report,
        &mut at,
    );
    if let Selection::Paths(paths) = selection {
        report.missing = matcher.missing(paths);
    }
    BlocksOutcome {
        stop_ordinal: result.is_err().then_some(at),
        report,
        result,
    }
}

fn run_blocks_loop(
    reader: &mut Reader,
    matcher: &mut Matcher,
    limits: &ExtractLimits,
    sink: &mut dyn BlockSink,
    cancel: &mut dyn FnMut() -> bool,
    report: &mut ExtractReport,
    at: &mut u32,
) -> Result<(), ArchiveError> {
    let mut selected: usize = 0;
    let mut running_total: u64 = 0;
    let mut since_poll: u32 = 0;
    let count_selected = |selected: &mut usize, entry: String| -> Result<(), ArchiveError> {
        *selected += 1;
        if *selected > limits.max_entries {
            return Err(ArchiveError::LimitExceeded {
                entry,
                rule: "entries",
            });
        }
        Ok(())
    };
    if matcher.selects_nothing() {
        return Ok(());
    }
    loop {
        // After every CANCEL_POLL_HEADERS headers read, before the next.
        if since_poll >= CANCEL_POLL_HEADERS {
            since_poll = 0;
            *at = reader.headers_read;
            if cancel() {
                return Err(ArchiveError::Cancelled);
            }
        }
        *at = reader.headers_read;
        let entry = match reader.next_header_raw() {
            Ok(Some(entry)) => {
                since_poll += 1;
                entry
            }
            Ok(None) => break,
            Err(ArchiveError::Failed(message)) => {
                // Counted (libarchive consumed it), reported when selected, never read.
                since_poll += 1;
                let ordinal = reader.current_ordinal();
                *at = ordinal;
                if matcher.selected_by_ordinal(ordinal) {
                    count_selected(&mut selected, format!("header {ordinal}"))?;
                    sink.failed(ordinal, FailKind::Decode, &message)?;
                    report.entries_failed += 1;
                }
                if matcher.past_end(ordinal) {
                    break;
                }
                continue;
            }
            Err(error) => return Err(error),
        };
        // SAFETY: `entry` was just returned by `next_header_raw` on this reader.
        let metadata = unsafe { reader.metadata(entry) }?;
        let ordinal = metadata.ordinal;
        *at = ordinal;
        if is_archive_root(&metadata) || !matcher.matches(&metadata) {
            if matcher.past_end(ordinal) {
                break;
            }
            continue;
        }
        count_selected(&mut selected, metadata.path.clone())?;
        if !sink.begin(&metadata)? {
            match metadata.kind {
                EntryKind::Symlink | EntryKind::Hardlink => report.skipped_links += 1,
                _ => report.skipped += 1,
            }
        } else if let Some(reason) =
            policy::structural_check(&metadata, limits.max_path_depth, limits.max_name_length)
        {
            // After `begin`, so a sink that declines a kind (links, for the provider adapter) is
            // never told about an entry it would not have written; a stale plan's unsafe path is
            // a FAIL right after its BEGIN, and no data is read.
            sink.failed(ordinal, FailKind::Other, reason)?;
            report.entries_failed += 1;
        } else if metadata.kind == EntryKind::File {
            let end = reader.stream_current_entry_data(
                &mut |block| sink.write(ordinal, block),
                &metadata,
                limits,
                &mut running_total,
            )?;
            match end {
                DataEnd::Complete { written, warning } => {
                    sink.end(ordinal, written, warning)?;
                    report.entries_written += 1;
                    report.bytes_written += written;
                }
                DataEnd::Failed { kind, message } => {
                    sink.failed(ordinal, kind, &message)?;
                    report.entries_failed += 1;
                }
            }
        } else {
            sink.end(ordinal, 0, None)?;
            report.entries_written += 1;
        }
        if matcher.past_end(ordinal) {
            break;
        }
    }
    Ok(())
}

/// A [Selection] made cheap to ask: normalised ranges, or the policy-keyed path set with what has
/// matched so far.
enum Matcher {
    All,
    Paths {
        wanted: HashSet<String>,
        matched: HashSet<String>,
    },
    Ranges {
        /// Sorted, merged, non-empty ranges.
        ranges: Vec<(u32, u32)>,
        /// The highest selected ordinal; `None` when the selection is empty.
        last: Option<u32>,
    },
}

impl Matcher {
    fn new(selection: &Selection) -> Self {
        match selection {
            Selection::All => Matcher::All,
            Selection::Paths(paths) => Matcher::Paths {
                wanted: paths
                    .iter()
                    .map(|path| policy::normalized_path_key(path))
                    .collect(),
                matched: HashSet::new(),
            },
            Selection::Ranges(ranges) => {
                let mut sorted: Vec<(u32, u32)> = ranges
                    .iter()
                    .copied()
                    .filter(|(first, last)| first <= last)
                    .collect();
                sorted.sort_unstable();
                let mut merged: Vec<(u32, u32)> = Vec::with_capacity(sorted.len());
                for (first, last) in sorted {
                    match merged.last_mut() {
                        Some((_, end)) if first <= end.saturating_add(1) => *end = (*end).max(last),
                        _ => merged.push((first, last)),
                    }
                }
                let last = merged.last().map(|(_, last)| *last);
                Matcher::Ranges {
                    ranges: merged,
                    last,
                }
            }
        }
    }

    fn selects_nothing(&self) -> bool {
        matches!(self, Matcher::Ranges { last: None, .. })
    }

    /// Whether `ordinal` is selected without knowing its path: always for `All`, by lookup for
    /// `Ranges`, never for `Paths` (a header without a readable path cannot match one).
    fn selected_by_ordinal(&self, ordinal: u32) -> bool {
        match self {
            Matcher::All => true,
            Matcher::Paths { .. } => false,
            Matcher::Ranges { ranges, .. } => ranges
                .binary_search_by(|(first, last)| {
                    if *last < ordinal {
                        std::cmp::Ordering::Less
                    } else if *first > ordinal {
                        std::cmp::Ordering::Greater
                    } else {
                        std::cmp::Ordering::Equal
                    }
                })
                .is_ok(),
        }
    }

    fn matches(&mut self, entry: &EntryMetadata) -> bool {
        match self {
            Matcher::Paths { wanted, matched } => {
                let key = policy::normalized_path_key(&entry.path);
                if !wanted.contains(&key) {
                    return false;
                }
                matched.insert(key);
                true
            }
            other => other.selected_by_ordinal(entry.ordinal),
        }
    }

    /// Whether nothing after `ordinal` can be selected (`Ranges` only).
    fn past_end(&self, ordinal: u32) -> bool {
        match self {
            Matcher::Ranges { last, .. } => last.is_none_or(|last| ordinal >= last),
            _ => false,
        }
    }

    fn missing(&self, paths: &[String]) -> Vec<String> {
        match self {
            Matcher::Paths { matched, .. } => paths
                .iter()
                .filter(|path| !matched.contains(&policy::normalized_path_key(path)))
                .cloned()
                .collect(),
            _ => Vec::new(),
        }
    }
}

/// The header pass that precedes an [extract_blocks] pass (M3.4 section 2.4): the archive's
/// length and the [EntryMetadata] of every selected entry, in archive order, for
/// [policy::evaluate_selection]. Reads no data; stops after the highest ordinal a
/// [Selection::Ranges] names; polls `cancel` every [CANCEL_POLL_HEADERS] headers. A header
/// libarchive cannot parse is passed over (it occupies its ordinal, the extraction pass reports it
/// failed); a fatal header error is `Err`. Cheap on ZIP/7-Zip/ISO (a table walk), a decompression
/// pass on `tar.*`.
pub fn inspect_for_extraction(
    fd: RawFd,
    selection: &Selection,
    cancel: &mut dyn FnMut() -> bool,
) -> Result<SelectedEntries, ArchiveError> {
    let mut reader = Reader::open_fd(fd)?;
    let mut matcher = Matcher::new(selection);
    let mut entries = Vec::new();
    let mut since_poll: u32 = 0;
    while !matcher.selects_nothing() {
        if since_poll >= CANCEL_POLL_HEADERS {
            since_poll = 0;
            if cancel() {
                return Err(ArchiveError::Cancelled);
            }
        }
        let entry = match reader.next_header_raw() {
            Ok(Some(entry)) => {
                since_poll += 1;
                entry
            }
            Ok(None) => break,
            Err(ArchiveError::Failed(_)) => {
                since_poll += 1;
                if matcher.past_end(reader.current_ordinal()) {
                    break;
                }
                continue;
            }
            Err(error) => return Err(error),
        };
        // SAFETY: `entry` was just returned by `next_header_raw` on this reader.
        let metadata = unsafe { reader.metadata(entry) }?;
        let ordinal = metadata.ordinal;
        if !is_archive_root(&metadata) && matcher.matches(&metadata) {
            entries.push(metadata);
        }
        if matcher.past_end(ordinal) {
            break;
        }
    }
    Ok(SelectedEntries {
        archive_bytes: reader.archive_bytes,
        entries,
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs::File;
    use std::io::Write;
    use std::os::unix::io::AsRawFd;
    use std::path::Path;
    use std::path::PathBuf;
    use std::process::Command;

    /// Builds a real, byte-correct `ar` archive via the system `ar` tool (part of binutils,
    /// present on every Ubuntu CI runner and this workspace's own toolchain) rather than
    /// hand-encoding `ar`'s binary header format: a hand-rolled header that happened to be
    /// internally consistent but subtly wrong against the real format would make this test
    /// validate nothing. `ar` needs no compression codec, matching this task's own zero-codec
    /// scope (see this file's own module doc comment).
    pub(crate) fn build_ar_fixture(dir: &Path, entries: &[(&str, &[u8])]) -> PathBuf {
        for (name, contents) in entries {
            File::create(dir.join(name))
                .unwrap()
                .write_all(contents)
                .unwrap();
        }
        let archive_path = dir.join("fixture.a");
        let status = Command::new("ar")
            .arg("rc")
            .arg(&archive_path)
            .args(entries.iter().map(|(name, _)| *name))
            .current_dir(dir)
            .status()
            .expect("the `ar` tool must be available to build this test's fixture");
        assert!(status.success(), "ar rc failed building the test fixture");
        archive_path
    }

    /// Opens one of the committed fixtures under `core/fixtures/`, generated by
    /// `tools/fixtures/make_compression_fixtures.py` -- whose `ENTRIES` are the same `hello.txt`/
    /// `second.txt` pair [build_ar_fixture]'s callers use, so the literals asserted against a
    /// compressed fixture below are the same ones asserted against the `ar` archive.
    pub(crate) fn open_fixture(name: &str) -> File {
        let path = Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("../../fixtures")
            .join(name);
        File::open(&path).unwrap_or_else(|e| panic!("opening fixture {}: {e}", path.display()))
    }

    #[test]
    fn entries_lists_every_member_without_reading_data() {
        let dir = tempdir();
        let archive_path = build_ar_fixture(
            dir.path(),
            &[
                ("hello.txt", b"hello world"),
                ("second.txt", b"more data, a bit longer"),
            ],
        );
        let file = File::open(&archive_path).unwrap();
        let listed = entries(file.as_raw_fd()).unwrap();
        let names: Vec<&str> = listed.iter().map(|e| e.path.as_str()).collect();
        assert_eq!(names, vec!["hello.txt", "second.txt"]);
        assert_eq!(listed[0].size, 11);
        assert_eq!(listed[1].size, 23);
        assert!(!listed[0].is_directory);
    }

    #[test]
    fn read_entry_returns_the_exact_original_bytes() {
        let dir = tempdir();
        let archive_path = build_ar_fixture(dir.path(), &[("hello.txt", b"hello world")]);
        let file = File::open(&archive_path).unwrap();
        let data = read_entry(file.as_raw_fd(), "hello.txt").unwrap();
        assert_eq!(data, Some(b"hello world".to_vec()));
    }

    #[test]
    fn read_entry_returns_none_for_a_missing_path() {
        let dir = tempdir();
        let archive_path = build_ar_fixture(dir.path(), &[("hello.txt", b"hello world")]);
        let file = File::open(&archive_path).unwrap();
        let data = read_entry(file.as_raw_fd(), "does-not-exist.txt").unwrap();
        assert_eq!(data, None);
    }

    #[test]
    fn an_uncompressed_archive_has_only_the_none_filter() {
        let dir = tempdir();
        let archive_path = build_ar_fixture(dir.path(), &[("hello.txt", b"hello world")]);
        let file = File::open(&archive_path).unwrap();
        assert_eq!(filter_names(file.as_raw_fd()).unwrap(), vec!["none"]);
    }

    #[test]
    fn lz4_sample_entries_lists_every_member() {
        let file = open_fixture("sample.tar.lz4");
        let listed = entries(file.as_raw_fd()).unwrap();
        assert_eq!(
            listed,
            vec![
                ArchiveEntry {
                    path: "hello.txt".to_string(),
                    size: 11,
                    is_directory: false,
                },
                ArchiveEntry {
                    path: "second.txt".to_string(),
                    size: 23,
                    is_directory: false,
                },
            ]
        );
    }

    #[test]
    fn lz4_sample_read_entry_returns_the_exact_original_bytes() {
        let file = open_fixture("sample.tar.lz4");
        let data = read_entry(file.as_raw_fd(), "hello.txt").unwrap();
        assert_eq!(data, Some(b"hello world".to_vec()));
        let file = open_fixture("sample.tar.lz4");
        let data = read_entry(file.as_raw_fd(), "second.txt").unwrap();
        assert_eq!(data, Some(b"more data, a bit longer".to_vec()));
    }

    #[test]
    fn lz4_sample_is_decoded_by_the_compiled_in_lz4_filter() {
        let file = open_fixture("sample.tar.lz4");
        assert_eq!(filter_names(file.as_raw_fd()).unwrap(), vec!["lz4", "none"]);
    }

    #[test]
    fn lz4_truncated_is_a_fatal_error_not_a_panic() {
        let file = open_fixture("truncated.tar.lz4");
        assert!(matches!(
            entries(file.as_raw_fd()),
            Err(ArchiveError::Fatal(_))
        ));
        let file = open_fixture("truncated.tar.lz4");
        assert!(matches!(
            read_entry(file.as_raw_fd(), "second.txt"),
            Err(ArchiveError::Fatal(_))
        ));
    }

    #[test]
    fn zstd_sample_entries_lists_every_member() {
        let file = open_fixture("sample.tar.zst");
        let listed = entries(file.as_raw_fd()).unwrap();
        assert_eq!(
            listed,
            vec![
                ArchiveEntry {
                    path: "hello.txt".to_string(),
                    size: 11,
                    is_directory: false,
                },
                ArchiveEntry {
                    path: "second.txt".to_string(),
                    size: 23,
                    is_directory: false,
                },
            ]
        );
    }

    #[test]
    fn zstd_sample_read_entry_returns_the_exact_original_bytes() {
        let file = open_fixture("sample.tar.zst");
        let data = read_entry(file.as_raw_fd(), "hello.txt").unwrap();
        assert_eq!(data, Some(b"hello world".to_vec()));
        let file = open_fixture("sample.tar.zst");
        let data = read_entry(file.as_raw_fd(), "second.txt").unwrap();
        assert_eq!(data, Some(b"more data, a bit longer".to_vec()));
    }

    #[test]
    fn zstd_sample_is_decoded_by_the_compiled_in_zstd_filter() {
        let file = open_fixture("sample.tar.zst");
        assert_eq!(
            filter_names(file.as_raw_fd()).unwrap(),
            vec!["zstd", "none"]
        );
    }

    #[test]
    fn zstd_truncated_is_a_fatal_error_not_a_panic() {
        let file = open_fixture("truncated.tar.zst");
        assert!(matches!(
            entries(file.as_raw_fd()),
            Err(ArchiveError::Fatal(_))
        ));
        let file = open_fixture("truncated.tar.zst");
        assert!(matches!(
            read_entry(file.as_raw_fd(), "second.txt"),
            Err(ArchiveError::Fatal(_))
        ));
    }

    #[test]
    fn gzip_sample_entries_lists_every_member() {
        let file = open_fixture("sample.tar.gz");
        let listed = entries(file.as_raw_fd()).unwrap();
        assert_eq!(
            listed,
            vec![
                ArchiveEntry {
                    path: "hello.txt".to_string(),
                    size: 11,
                    is_directory: false,
                },
                ArchiveEntry {
                    path: "second.txt".to_string(),
                    size: 23,
                    is_directory: false,
                },
            ]
        );
    }

    #[test]
    fn gzip_sample_read_entry_returns_the_exact_original_bytes() {
        let file = open_fixture("sample.tar.gz");
        let data = read_entry(file.as_raw_fd(), "hello.txt").unwrap();
        assert_eq!(data, Some(b"hello world".to_vec()));
        let file = open_fixture("sample.tar.gz");
        let data = read_entry(file.as_raw_fd(), "second.txt").unwrap();
        assert_eq!(data, Some(b"more data, a bit longer".to_vec()));
    }

    #[test]
    fn gzip_sample_is_decoded_by_the_compiled_in_gzip_filter() {
        let file = open_fixture("sample.tar.gz");
        assert_eq!(
            filter_names(file.as_raw_fd()).unwrap(),
            vec!["gzip", "none"]
        );
    }

    #[test]
    fn gzip_truncated_is_a_fatal_error_not_a_panic() {
        let file = open_fixture("truncated.tar.gz");
        assert!(matches!(
            entries(file.as_raw_fd()),
            Err(ArchiveError::Fatal(_))
        ));
        let file = open_fixture("truncated.tar.gz");
        assert!(matches!(
            read_entry(file.as_raw_fd(), "second.txt"),
            Err(ArchiveError::Fatal(_))
        ));
    }

    #[test]
    fn bzip2_sample_entries_lists_every_member() {
        let file = open_fixture("sample.tar.bz2");
        let listed = entries(file.as_raw_fd()).unwrap();
        assert_eq!(
            listed,
            vec![
                ArchiveEntry {
                    path: "hello.txt".to_string(),
                    size: 11,
                    is_directory: false,
                },
                ArchiveEntry {
                    path: "second.txt".to_string(),
                    size: 23,
                    is_directory: false,
                },
            ]
        );
    }

    #[test]
    fn bzip2_sample_read_entry_returns_the_exact_original_bytes() {
        let file = open_fixture("sample.tar.bz2");
        let data = read_entry(file.as_raw_fd(), "hello.txt").unwrap();
        assert_eq!(data, Some(b"hello world".to_vec()));
        let file = open_fixture("sample.tar.bz2");
        let data = read_entry(file.as_raw_fd(), "second.txt").unwrap();
        assert_eq!(data, Some(b"more data, a bit longer".to_vec()));
    }

    #[test]
    fn bzip2_sample_is_decoded_by_the_compiled_in_bzip2_filter() {
        let file = open_fixture("sample.tar.bz2");
        assert_eq!(
            filter_names(file.as_raw_fd()).unwrap(),
            vec!["bzip2", "none"]
        );
    }

    #[test]
    fn bzip2_truncated_is_a_fatal_error_not_a_panic() {
        let file = open_fixture("truncated.tar.bz2");
        assert!(matches!(
            entries(file.as_raw_fd()),
            Err(ArchiveError::Fatal(_))
        ));
        let file = open_fixture("truncated.tar.bz2");
        assert!(matches!(
            read_entry(file.as_raw_fd(), "second.txt"),
            Err(ArchiveError::Fatal(_))
        ));
    }

    #[test]
    fn xz_sample_entries_lists_every_member() {
        let file = open_fixture("sample.tar.xz");
        let listed = entries(file.as_raw_fd()).unwrap();
        assert_eq!(
            listed,
            vec![
                ArchiveEntry {
                    path: "hello.txt".to_string(),
                    size: 11,
                    is_directory: false,
                },
                ArchiveEntry {
                    path: "second.txt".to_string(),
                    size: 23,
                    is_directory: false,
                },
            ]
        );
    }

    #[test]
    fn xz_sample_read_entry_returns_the_exact_original_bytes() {
        let file = open_fixture("sample.tar.xz");
        let data = read_entry(file.as_raw_fd(), "hello.txt").unwrap();
        assert_eq!(data, Some(b"hello world".to_vec()));
        let file = open_fixture("sample.tar.xz");
        let data = read_entry(file.as_raw_fd(), "second.txt").unwrap();
        assert_eq!(data, Some(b"more data, a bit longer".to_vec()));
    }

    #[test]
    fn xz_sample_is_decoded_by_the_compiled_in_xz_filter() {
        let file = open_fixture("sample.tar.xz");
        assert_eq!(filter_names(file.as_raw_fd()).unwrap(), vec!["xz", "none"]);
    }

    #[test]
    fn xz_truncated_is_a_fatal_error_not_a_panic() {
        let file = open_fixture("truncated.tar.xz");
        assert!(matches!(
            entries(file.as_raw_fd()),
            Err(ArchiveError::Fatal(_))
        ));
        let file = open_fixture("truncated.tar.xz");
        assert!(matches!(
            read_entry(file.as_raw_fd(), "second.txt"),
            Err(ArchiveError::Fatal(_))
        ));
    }

    /// ZIP method 8 (deflate) is what zlib unlocks beyond the gzip filter: without `HAVE_ZLIB_H`
    /// libarchive's ZIP reader lists deflated entries but cannot read their data. No filter is
    /// involved (`["none"]`) -- the decoding happens inside the format reader.
    #[test]
    fn deflated_zip_read_entry_returns_the_exact_original_bytes() {
        let file = open_fixture("sample-deflate.zip");
        assert_eq!(filter_names(file.as_raw_fd()).unwrap(), vec!["none"]);
        let file = open_fixture("sample-deflate.zip");
        let names: Vec<String> = entries(file.as_raw_fd())
            .unwrap()
            .into_iter()
            .map(|e| e.path)
            .collect();
        assert_eq!(names, vec!["hello.txt", "second.txt"]);
        let file = open_fixture("sample-deflate.zip");
        let data = read_entry(file.as_raw_fd(), "hello.txt").unwrap();
        assert_eq!(data, Some(b"hello world".to_vec()));
        let file = open_fixture("sample-deflate.zip");
        let data = read_entry(file.as_raw_fd(), "second.txt").unwrap();
        assert_eq!(data, Some(b"more data, a bit longer".to_vec()));
    }

    /// No format bids on the first header: `Unsupported`, the design's own variant for "not an
    /// archive we can open", rather than `Fatal` ("damaged") -- and never a panic.
    #[test]
    fn a_non_archive_is_unsupported_not_a_panic() {
        let dir = tempdir();
        let path = dir.path().join("not-an-archive");
        File::create(&path)
            .unwrap()
            .write_all(b"this is not an archive of any kind")
            .unwrap();
        let file = File::open(&path).unwrap();
        let result = entries(file.as_raw_fd());
        assert!(
            matches!(result, Err(ArchiveError::Unsupported(ref m)) if m.contains("Unrecognized")),
            "{result:?}"
        );
    }

    /// A tiny, dependency-free stand-in for a `tempfile`-style crate: this crate deliberately adds
    /// no dev-dependency for a handful of tests, matching the project's own "smallest working
    /// thing first" convention. A directory under `std::env::temp_dir()` named with the process
    /// id, an incrementing counter and the current time is unique enough for tests that never run
    /// the same process twice concurrently under the same name, and is removed on drop.
    pub(crate) struct TempDir(PathBuf);
    impl TempDir {
        pub(crate) fn path(&self) -> &Path {
            &self.0
        }
    }
    impl Drop for TempDir {
        fn drop(&mut self) {
            let _ = std::fs::remove_dir_all(&self.0);
        }
    }
    pub(crate) fn tempdir() -> TempDir {
        use std::sync::atomic::AtomicU32;
        use std::sync::atomic::Ordering;
        static COUNTER: AtomicU32 = AtomicU32::new(0);
        let n = COUNTER.fetch_add(1, Ordering::Relaxed);
        let nanos = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap()
            .as_nanos();
        let path = std::env::temp_dir().join(format!(
            "fylz-archive-test-{}-{}-{}",
            std::process::id(),
            n,
            nanos
        ));
        std::fs::create_dir_all(&path).unwrap();
        TempDir(path)
    }
}
