//! Archive read engine over libarchive (BSD-licensed C library, vendored as a git submodule at
//! `core/third_party/libarchive`, cross-compiled by this crate's own `build.rs` -- never a Cargo
//! dependency, so nothing about it appears in `cargo tree`/`cargo deny check`'s own dependency
//! graph; see `build.rs`'s own doc comment for why). M3.1's read path: [entries]/[read_entry]/
//! [filter_names] (part 1), all five compression backends `build.rs` vendors compiled in (lz4,
//! zstd, zlib, bzip2 and xz -- parts 2a-2e, each proven by a fixture pair under `core/fixtures/`
//! generated by `tools/fixtures/make_compression_fixtures.py`), the extraction [policy] ported from
//! the app's `ArchiveExtractionPolicy.kt` (part 3a), and [inspect]/[inspect_with_policy] plus the
//! streaming [extract] with runtime limits (part 3b), all over one seekable file descriptor.
//!
//! **Input contract** (`docs/agent/DESIGN-M32-SEEKABLE-PFD.md` section 2.1): every public function
//! takes a raw fd that must refer to a regular file. The shared open path `fstat`s it and refuses
//! anything else with [ArchiveError::NotSeekable], then rewinds it to byte 0 -- a correctness
//! requirement, not hygiene: libarchive's fd reader seeks absolutely (`open_fd.c`) but treats the
//! first byte it reads as offset 0, so the seekable ZIP reader and 7z would read the wrong bytes
//! from a descriptor left at a non-zero offset. Pipes never reach the engine (the app stages
//! non-seekable input to cache first); `Reader::open_unchecked` exists for tests that want to
//! feed one anyway.

pub mod policy;

#[cfg(test)]
mod extract_tests;
#[cfg(test)]
mod policy_tests;

pub use policy::Decision;
pub use policy::EntryKind;
pub use policy::EntryMetadata;
pub use policy::Limits;

use std::collections::HashSet;
use std::ffi::CStr;
use std::fs::File;
use std::io::Seek;
use std::io::SeekFrom;
use std::io::Write;
use std::mem::ManuallyDrop;
use std::os::fd::AsRawFd;
use std::os::fd::BorrowedFd;
use std::os::fd::FromRawFd;
use std::os::raw::c_int;
use std::os::raw::c_void;
use std::os::unix::fs::FileTypeExt;
use std::os::unix::io::RawFd;

mod sys {
    //! Hand-written declarations for the small slice of libarchive's C API this crate calls --
    //! not machine-generated (no bindgen dependency pulled in for a couple of dozen stable,
    //! decades-old functions), and not exhaustive: extend this module rather than reaching for a
    //! `-sys` crate or bindgen wholesale, so this file stays the one place documenting exactly
    //! what is used and why. Every declaration below was checked against
    //! `core/third_party/libarchive/libarchive/archive.h`/`archive_entry.h` at v3.8.9.
    //!
    //! `LaSsizeT`/`LaInt64T` are libarchive's own portable typedefs (`archive.h`'s `la_ssize_t`/
    //! `la_int64_t`), guaranteed 64-bit on every platform including 32-bit ones, for large-file
    //! support. `Mode` (`archive_entry_filetype`/`archive_entry_perm`'s return type,
    //! `archive_entry.h`'s `__LA_MODE_T`) is `mode_t`, confirmed `unsigned int` (`c_uint`, 32-bit)
    //! on every target this crate builds for: the Android NDK sysroot's
    //! `asm-generic/posix_types.h` defines `__kernel_mode_t` as `unsigned int` for
    //! aarch64/armv7/x86_64 alike, and glibc matches on the host. `archive_entry_mtime` returns
    //! `time_t`, which is `long` -- **32-bit on `armv7-linux-androideabi`** (bionic) and 64-bit
    //! everywhere else this crate builds -- so it is declared `c_long`, never `i64`, and widened
    //! by the caller. Getting either width wrong on the 32-bit target would be a silent ABI
    //! mismatch, not a compile error -- confirmed against the real headers rather than assumed.
    use std::os::raw::c_char;
    use std::os::raw::c_int;
    use std::os::raw::c_long;
    use std::os::raw::c_void;

    #[repr(C)]
    pub struct Archive {
        _private: [u8; 0],
    }
    #[repr(C)]
    pub struct ArchiveEntry {
        _private: [u8; 0],
    }

    pub type LaSsizeT = isize;
    pub type LaInt64T = i64;
    pub type Mode = u32;
    pub type TimeT = c_long;

    unsafe extern "C" {
        pub fn archive_read_new() -> *mut Archive;
        pub fn archive_read_support_filter_all(a: *mut Archive) -> c_int;
        pub fn archive_read_support_format_all(a: *mut Archive) -> c_int;
        pub fn archive_read_open_fd(a: *mut Archive, fd: c_int, block_size: usize) -> c_int;
        pub fn archive_read_next_header(a: *mut Archive, entry: *mut *mut ArchiveEntry) -> c_int;
        pub fn archive_read_data(a: *mut Archive, buf: *mut c_void, len: usize) -> LaSsizeT;
        pub fn archive_read_data_block(
            a: *mut Archive,
            buff: *mut *const c_void,
            size: *mut usize,
            offset: *mut LaInt64T,
        ) -> c_int;
        pub fn archive_read_has_encrypted_entries(a: *mut Archive) -> c_int;
        pub fn archive_read_free(a: *mut Archive) -> c_int;
        pub fn archive_error_string(a: *mut Archive) -> *const c_char;
        pub fn archive_filter_count(a: *mut Archive) -> c_int;
        pub fn archive_filter_name(a: *mut Archive, n: c_int) -> *const c_char;
        pub fn archive_format(a: *mut Archive) -> c_int;
        pub fn archive_format_name(a: *mut Archive) -> *const c_char;

        pub fn archive_entry_pathname(e: *mut ArchiveEntry) -> *const c_char;
        pub fn archive_entry_hardlink(e: *mut ArchiveEntry) -> *const c_char;
        pub fn archive_entry_symlink(e: *mut ArchiveEntry) -> *const c_char;
        pub fn archive_entry_size(e: *mut ArchiveEntry) -> LaInt64T;
        pub fn archive_entry_size_is_set(e: *mut ArchiveEntry) -> c_int;
        pub fn archive_entry_filetype(e: *mut ArchiveEntry) -> Mode;
        pub fn archive_entry_perm(e: *mut ArchiveEntry) -> Mode;
        pub fn archive_entry_mtime(e: *mut ArchiveEntry) -> TimeT;
        pub fn archive_entry_mtime_is_set(e: *mut ArchiveEntry) -> c_int;
        pub fn archive_entry_is_data_encrypted(e: *mut ArchiveEntry) -> c_int;
        pub fn archive_entry_is_metadata_encrypted(e: *mut ArchiveEntry) -> c_int;
    }
}

const ARCHIVE_EOF: c_int = 1;
const ARCHIVE_OK: c_int = 0;
const ARCHIVE_WARN: c_int = -20;

/// `archive.h`'s format-family mask and the one family code this crate needs to name (7-Zip,
/// whose encrypted-header failure is reported as [ArchiveError::Unsupported]).
const ARCHIVE_FORMAT_BASE_MASK: c_int = 0xff0000;
const ARCHIVE_FORMAT_7ZIP: c_int = 0xE0000;

/// `archive_entry.h`'s `AE_IFMT` and the file-type values this crate tells apart; every other
/// type (device nodes, fifos, sockets) is [EntryKind::Other].
const AE_IFMT: u32 = 0o170000;
const AE_IFREG: u32 = 0o100000;
const AE_IFLNK: u32 = 0o120000;
const AE_IFDIR: u32 = 0o040000;

/// One member of the simple listing ([entries]) and the value [DestinationProvider] is offered per
/// selected entry during [extract]. Unchanged since part 1; the richer per-entry shape is
/// [EntryMetadata], which [inspect] collects.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ArchiveEntry {
    pub path: String,
    pub size: i64,
    pub is_directory: bool,
}

impl ArchiveEntry {
    fn from_metadata(metadata: &EntryMetadata) -> Self {
        ArchiveEntry {
            path: metadata.path.clone(),
            // `archive_entry_size` reads 0 when the size is unset, which is what `uncompressed:
            // None` came from.
            size: metadata
                .uncompressed
                .and_then(|size| i64::try_from(size).ok())
                .unwrap_or(0),
            is_directory: metadata.kind == EntryKind::Directory,
        }
    }
}

#[derive(Debug)]
pub enum ArchiveError {
    /// `fstat` says the descriptor is not a regular file; the text names what it is
    /// (`"not seekable (fifo)"`). The app never sends one (non-seekable input is staged to cache
    /// first), so seeing this is a caller bug, not a user-facing condition.
    NotSeekable(String),
    /// libarchive could not recognise the input as any archive format it knows (no format bid at
    /// open: `archive_format() == 0`, "Unrecognized archive format"), or recognised a 7-Zip
    /// archive whose header is itself encrypted (the message contains "encrypted"), which this
    /// build cannot read. Distinct from [ArchiveError::Fatal] so the app can say "not an archive
    /// we can open" rather than "damaged".
    Unsupported(String),
    /// libarchive itself reported a fatal error mid-way; the message is `archive_error_string`'s
    /// own text. Also carries this crate's own few internal failures (`fstat`/`lseek`/destination
    /// write errors), each prefixed with what failed.
    Fatal(String),
    /// An entry's pathname was not valid UTF-8. Returned only by the exact-match lookups
    /// ([entries] and [read_entry]): an exact match against a lossily decoded name would be
    /// ambiguous, so those keep failing loudly until M3.7 gives legacy ZIP names a real charset.
    /// [inspect] and [extract] never return it -- they decode such a name with
    /// `String::from_utf8_lossy` and flag it with [EntryMetadata::name_lossy].
    NonUtf8Path,
    /// A runtime limit stopped the operation. `rule` names the limit: `"listing"`
    /// ([Limits::max_listing_entries], from [inspect]); `"entries"`, `"file"`, `"declared"` and
    /// `"total"` (from [extract]: [ExtractLimits::max_entries], [ExtractLimits::max_file_bytes], an
    /// entry's data exceeding its own declared size, [ExtractLimits::max_total_uncompressed_bytes]).
    /// `entry` is the path of the entry being processed when the limit hit.
    LimitExceeded { entry: String, rule: &'static str },
}

impl std::fmt::Display for ArchiveError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            ArchiveError::NotSeekable(message) => write!(f, "{message}"),
            ArchiveError::Unsupported(message) => write!(f, "unsupported archive: {message}"),
            ArchiveError::Fatal(message) => write!(f, "{message}"),
            ArchiveError::NonUtf8Path => write!(f, "entry pathname is not valid UTF-8"),
            ArchiveError::LimitExceeded { entry, rule } => {
                write!(f, "limit exceeded ({rule}) at entry {entry:?}")
            }
        }
    }
}

impl std::error::Error for ArchiveError {}

/// What [inspect] learns from one header pass over an archive.
#[derive(Debug, Clone, PartialEq)]
pub struct Inspection {
    /// The archive file's own length, from `fstat` on the descriptor.
    pub archive_bytes: u64,
    /// `archive_format() & ARCHIVE_FORMAT_BASE_MASK` after the first header: the format
    /// *family* (`0x30000` tar, `0x50000` ZIP, `0x70000` ar, `0xE0000` 7-Zip, ...; `0x60000` for
    /// an empty archive), which is what callers key decisions on.
    pub format_code: u32,
    /// `archive_format_name`, informational only: for ZIP it names the *current entry's*
    /// compression method, and it is `None` for an archive with no entries.
    pub format_name: Option<String>,
    /// The compression filters between the file and the format reader (`["gzip"]`, `["xz"]`,
    /// ...), libarchive's own always-present `"none"` filter dropped, so a plain archive is `[]`.
    pub filters: Vec<String>,
    /// `archive_read_has_encrypted_entries`: `Some(true)`/`Some(false)` when the format reader
    /// can tell (ZIP, 7-Zip, RAR), `None` when it cannot or the format has no notion of it (tar).
    pub has_encrypted_entries: Option<bool>,
    pub entries: Vec<EntryMetadata>,
}

/// Which entries [extract] writes.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Selection {
    All,
    /// Exact entry paths, matched after the same normalisation the policy uses for duplicate
    /// detection (backslashes to slashes, trailing slashes trimmed, lower-cased), so a path taken
    /// from an [Inspection] always matches its own entry. A requested path with no entry is
    /// reported in [ExtractReport::missing], never an error.
    Paths(Vec<String>),
}

/// The limits [extract] enforces while it runs -- against the bytes actually produced, not the
/// headers' claims, which is what makes them the real defence behind the policy's preflight.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ExtractLimits {
    pub max_file_bytes: u64,
    pub max_total_uncompressed_bytes: u64,
    pub max_entries: usize,
}

impl From<&Limits> for ExtractLimits {
    fn from(limits: &Limits) -> Self {
        ExtractLimits {
            max_file_bytes: limits.max_file_bytes,
            max_total_uncompressed_bytes: limits.max_total_uncompressed_bytes,
            max_entries: limits.max_entries,
        }
    }
}

impl Default for ExtractLimits {
    fn default() -> Self {
        ExtractLimits::from(&Limits::default())
    }
}

/// Where [extract] writes. The engine never creates, names or closes anything: the caller
/// (Kotlin's operation engine, through SAF) owns every destination and its lifetime.
pub trait DestinationProvider {
    /// Called once per selected entry, in archive order, for every kind but links (which are
    /// never materialised -- see [ExtractReport::skipped_links]) and `Other` (device nodes and
    /// the like, which SAF cannot create either). Return `Ok(None)` to skip it (directories, or a
    /// caller that decides not to write this one). The provider owns the fd's lifetime; the
    /// engine writes and flushes, never closes.
    fn open(&mut self, entry: &ArchiveEntry) -> Result<Option<BorrowedFd<'_>>, ArchiveError>;
    /// Called after an entry's data has been fully written and flushed to the fd `open` returned.
    fn done(&mut self, entry: &ArchiveEntry, bytes_written: u64) -> Result<(), ArchiveError>;
}

/// What [extract] did. On an `Err` there is no report: whatever was written before the failure
/// stays where it is, and the caller (staging, journal, recycle) owns cleanup, exactly as the
/// Kotlin `extractBounded` did -- `extract` never deletes.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct ExtractReport {
    /// Entries whose data was written and reported to [DestinationProvider::done].
    pub entries_written: usize,
    pub bytes_written: u64,
    /// Selected entries the provider declined (`Ok(None)`), plus `Other`-kind entries the engine
    /// never offered.
    pub skipped: usize,
    /// Selected symlink and hardlink entries, which the engine never offers to the provider.
    pub skipped_links: usize,
    /// `Selection::Paths` entries no archive entry matched, in the order requested.
    pub missing: Vec<String>,
}

/// Wraps a caller-owned raw fd as a `File` that is never closed: `ManuallyDrop` suppresses the
/// `close(2)` in `File::drop`, so the descriptor's lifetime stays entirely the caller's.
///
/// SAFETY (for the callers): `fd` must be open for the whole time the returned value is used;
/// every public function here documents that as its own contract on the caller.
fn borrow_fd(fd: RawFd) -> ManuallyDrop<File> {
    // SAFETY: see the function's own doc comment; the `ManuallyDrop` is what keeps this from
    // taking ownership (closing) the caller's descriptor.
    ManuallyDrop::new(unsafe { File::from_raw_fd(fd) })
}

/// Names a non-regular file type for [ArchiveError::NotSeekable]'s message.
fn describe_file_type(file_type: std::fs::FileType) -> &'static str {
    if file_type.is_fifo() {
        "fifo"
    } else if file_type.is_socket() {
        "socket"
    } else if file_type.is_char_device() {
        "character device"
    } else if file_type.is_block_device() {
        "block device"
    } else if file_type.is_dir() {
        "directory"
    } else {
        "unknown file type"
    }
}

/// Widens libarchive's `time_t` (`c_long`: 32-bit on armv7 bionic, 64-bit elsewhere) to the
/// `i64` [EntryMetadata::mtime] carries. A plain `as` because `i64::from` does not exist for the
/// 64-bit `c_long` (it is already `i64` there); clippy would flag the no-op on those hosts.
#[allow(clippy::unnecessary_cast)]
fn widen_time(t: sys::TimeT) -> i64 {
    t as i64
}

/// Owns a libarchive read handle for exactly one forward pass over a seekable fd -- opening it
/// twice (e.g. once for [entries] and again for [read_entry]) needs two `Reader`s, each of which
/// rewinds the descriptor to byte 0 first; this struct's `Drop` calls `archive_read_free`
/// (`archive_read_close` included). Random access within one pass is libarchive's own business
/// (the seekable ZIP reader jumps to the central directory; 7z seeks to its packs), which is why
/// the descriptor must be a regular file.
struct Reader {
    raw: *mut sys::Archive,
    /// The archive file's length from `fstat` at open (0 for a test-only unchecked pipe).
    archive_bytes: u64,
}

impl Reader {
    /// The shared open path of every public function: `fstat` -> [ArchiveError::NotSeekable]
    /// unless a regular file, `lseek(fd, 0, SEEK_SET)` (see the crate doc: libarchive seeks
    /// absolutely but treats the first byte read as offset 0, so the descriptor's current offset
    /// must be 0 whatever the caller left it at), then libarchive's own open.
    fn open_fd(fd: RawFd) -> Result<Self, ArchiveError> {
        let mut file = borrow_fd(fd);
        let metadata = file
            .metadata()
            .map_err(|e| ArchiveError::Fatal(format!("fstat on the archive descriptor: {e}")))?;
        let file_type = metadata.file_type();
        if !file_type.is_file() {
            return Err(ArchiveError::NotSeekable(format!(
                "not seekable ({})",
                describe_file_type(file_type)
            )));
        }
        file.seek(SeekFrom::Start(0))
            .map_err(|e| ArchiveError::Fatal(format!("lseek to the start of the archive: {e}")))?;
        Self::open_positioned(fd, metadata.len())
    }

    /// [Reader::open_fd] without the regular-file check, and with a failed rewind ignored, so a
    /// test can feed a pipe (`std::io::pipe()`) and show what the seekable contract buys -- the
    /// M3.2 negative controls. Never reachable from the public API.
    #[cfg(test)]
    fn open_unchecked(fd: RawFd) -> Result<Self, ArchiveError> {
        let mut file = borrow_fd(fd);
        let archive_bytes = file.metadata().map(|m| m.len()).unwrap_or(0);
        let _ = file.seek(SeekFrom::Start(0));
        Self::open_positioned(fd, archive_bytes)
    }

    fn open_positioned(fd: RawFd, archive_bytes: u64) -> Result<Self, ArchiveError> {
        // SAFETY: `archive_read_new` returns either a valid, freshly allocated `*mut Archive` or
        // null on allocation failure -- the null check below is this call's own safety contract.
        let raw = unsafe { sys::archive_read_new() };
        if raw.is_null() {
            return Err(ArchiveError::Fatal("archive_read_new returned null".into()));
        }
        let reader = Reader { raw, archive_bytes };
        // SAFETY: `raw` is a valid, just-allocated archive handle; `support_filter_all`/
        // `support_format_all` never fail in a way libarchive treats as fatal here (registering a
        // codec that is not actually compiled in is documented as harmless -- it simply cannot be
        // used later), so their return values are intentionally not checked.
        unsafe {
            sys::archive_read_support_filter_all(reader.raw);
            sys::archive_read_support_format_all(reader.raw);
        }
        // 64 KiB matches this crate's own streaming read-data buffer below and libarchive's own
        // commonly recommended default; it only affects the size of internal read()s against
        // `fd`, never correctness.
        let status = unsafe { sys::archive_read_open_fd(reader.raw, fd, 64 * 1024) };
        if let Err(error) = reader.check(status) {
            return Err(reader.classify_open_error(error));
        }
        Ok(reader)
    }

    /// Splits [ArchiveError::Unsupported] off from an open failure. libarchive runs the format
    /// bidding inside `archive_read_open_fd` (not, as one might expect, at the first
    /// `archive_read_next_header`), so "no format recognised this input" surfaces here: no bidder
    /// won (`archive_format() == 0`) and the message is `archive_read.c`'s own "Unrecognized
    /// archive format". Both are required -- a filter failing on a badly truncated stream also
    /// leaves the format at 0, and that is damage, not an unsupported format.
    fn classify_open_error(&self, error: ArchiveError) -> ArchiveError {
        let ArchiveError::Fatal(message) = error else {
            return error;
        };
        // SAFETY: `self.raw` is a valid archive handle (open failed, but the handle is live until
        // `Drop`).
        let format = unsafe { sys::archive_format(self.raw) };
        if format == 0 && message == "Unrecognized archive format" {
            return ArchiveError::Unsupported(message);
        }
        ArchiveError::Fatal(message)
    }

    /// Turns a non-OK, non-EOF, non-warning libarchive status into this crate's own error type,
    /// reading the message while `self.raw` is still valid -- a caller must never call this after
    /// the reader has already been freed.
    fn check(&self, status: c_int) -> Result<(), ArchiveError> {
        if status == ARCHIVE_OK || status == ARCHIVE_EOF || status == ARCHIVE_WARN {
            return Ok(());
        }
        Err(ArchiveError::Fatal(self.error_message(status)))
    }

    fn error_message(&self, status: c_int) -> String {
        // SAFETY: `self.raw` is non-null and owned by this `Reader` for its whole lifetime.
        unsafe {
            let ptr = sys::archive_error_string(self.raw);
            if ptr.is_null() {
                format!("libarchive error {status}")
            } else {
                CStr::from_ptr(ptr).to_string_lossy().into_owned()
            }
        }
    }

    /// The names of the filters libarchive put between `fd` and the format reader. Final as soon
    /// as [Reader::open_fd] has returned: `archive_read_open_fd` runs both the filter and the
    /// format bidding before it returns.
    fn filter_names(&self) -> Vec<String> {
        // SAFETY: `self.raw` is a valid, open archive handle; `archive_filter_name` returns null
        // or a pointer into storage libarchive owns for as long as the handle lives, which this
        // `Reader` does for the whole of this call.
        unsafe {
            let count = sys::archive_filter_count(self.raw);
            (0..count)
                .map(|n| {
                    let ptr = sys::archive_filter_name(self.raw, n);
                    if ptr.is_null() {
                        "(unnamed)".to_string()
                    } else {
                        CStr::from_ptr(ptr).to_string_lossy().into_owned()
                    }
                })
                .collect()
        }
    }

    /// `archive_format() & ARCHIVE_FORMAT_BASE_MASK`: the format family, meaningful once the
    /// first header (or EOF) has been read.
    fn format_code(&self) -> u32 {
        // SAFETY: `self.raw` is a valid, open archive handle.
        let format = unsafe { sys::archive_format(self.raw) };
        (format & ARCHIVE_FORMAT_BASE_MASK) as u32
    }

    fn format_name(&self) -> Option<String> {
        // SAFETY: `self.raw` is valid and open; the returned pointer is null or into storage
        // libarchive owns for as long as the handle lives.
        unsafe {
            let ptr = sys::archive_format_name(self.raw);
            if ptr.is_null() {
                None
            } else {
                Some(CStr::from_ptr(ptr).to_string_lossy().into_owned())
            }
        }
    }

    /// `archive_read_has_encrypted_entries`, asked after the header pass so a format reader that
    /// learns it per entry (ZIP) has seen them all: `Some` for a definite yes/no, `None` for
    /// `ARCHIVE_READ_FORMAT_ENCRYPTION_UNSUPPORTED`/`_DONT_KNOW`.
    fn has_encrypted_entries(&self) -> Option<bool> {
        // SAFETY: `self.raw` is a valid, open archive handle.
        match unsafe { sys::archive_read_has_encrypted_entries(self.raw) } {
            n if n > 0 => Some(true),
            0 => Some(false),
            _ => None,
        }
    }

    /// Advances to the next entry's header, returning `None` at end of archive and otherwise a
    /// pointer libarchive owns, valid until the next call on this reader. Per libarchive's own
    /// documented contract, calling this again before draining a prior entry's data silently
    /// skips whatever of that entry's body was never read -- exactly what [entries] and
    /// [inspect] rely on to list every entry without reading any data, and what [extract] relies
    /// on to pass over unselected entries.
    fn next_header(&mut self) -> Result<Option<*mut sys::ArchiveEntry>, ArchiveError> {
        let mut entry_ptr: *mut sys::ArchiveEntry = std::ptr::null_mut();
        // SAFETY: `self.raw` is a valid, open archive handle; `entry_ptr` is an out-parameter
        // libarchive sets to point at internally-owned storage that stays valid until the next
        // `archive_read_next_header`/`archive_read_free` call on this same `self.raw`.
        let status = unsafe { sys::archive_read_next_header(self.raw, &mut entry_ptr) };
        if status == ARCHIVE_EOF {
            return Ok(None);
        }
        if let Err(error) = self.check(status) {
            return Err(self.classify_header_error(error));
        }
        if entry_ptr.is_null() {
            return Err(ArchiveError::Fatal(
                "archive_read_next_header reported success with a null entry".into(),
            ));
        }
        Ok(Some(entry_ptr))
    }

    /// Splits [ArchiveError::Unsupported] off from a header-read failure: a 7-Zip archive whose
    /// header itself is encrypted (`7zip.c`: "The %s is encrypted, but currently not supported",
    /// raised while reading the first header, after the reader has set its format). Everything
    /// else stays `Fatal` -- an unrecognised format never gets this far, see
    /// [Reader::classify_open_error].
    fn classify_header_error(&self, error: ArchiveError) -> ArchiveError {
        let ArchiveError::Fatal(message) = error else {
            return error;
        };
        // SAFETY: `self.raw` is a valid, open archive handle.
        let format = unsafe { sys::archive_format(self.raw) };
        if format & ARCHIVE_FORMAT_BASE_MASK == ARCHIVE_FORMAT_7ZIP && message.contains("encrypted")
        {
            return ArchiveError::Unsupported(message);
        }
        ArchiveError::Fatal(message)
    }

    /// The raw bytes of the current entry's pathname, exactly as stored (libarchive passes
    /// non-UTF-8 names through untouched off Windows).
    ///
    /// SAFETY (for callers): `entry` must be the pointer the most recent [Reader::next_header]
    /// returned, on a reader that has not been advanced since.
    unsafe fn pathname_bytes<'a>(entry: *mut sys::ArchiveEntry) -> Result<&'a [u8], ArchiveError> {
        // SAFETY: per this function's own contract, `entry` is libarchive-owned and valid; the
        // pathname pointer is null or a NUL-terminated string owned by the same entry.
        let ptr = unsafe { sys::archive_entry_pathname(entry) };
        if ptr.is_null() {
            return Err(ArchiveError::Fatal("archive entry has no pathname".into()));
        }
        Ok(unsafe { CStr::from_ptr(ptr) }.to_bytes())
    }

    /// The simple listing shape of the current entry, failing with [ArchiveError::NonUtf8Path]
    /// on a name that is not UTF-8 (see that variant for why the lookups keep this strictness).
    ///
    /// SAFETY (for callers): as [Reader::pathname_bytes].
    unsafe fn listing_entry(entry: *mut sys::ArchiveEntry) -> Result<ArchiveEntry, ArchiveError> {
        // SAFETY: forwarded from this function's own contract.
        let path = std::str::from_utf8(unsafe { Self::pathname_bytes(entry) }?)
            .map_err(|_| ArchiveError::NonUtf8Path)?
            .to_string();
        // SAFETY: same `entry` validity as above.
        let (size, filetype) = unsafe {
            (
                sys::archive_entry_size(entry),
                sys::archive_entry_filetype(entry),
            )
        };
        Ok(ArchiveEntry {
            path,
            size,
            is_directory: filetype & AE_IFMT == AE_IFDIR,
        })
    }

    /// The full [EntryMetadata] of the current entry. Never fails on a name: a non-UTF-8 one is
    /// decoded lossily and flagged. Hardlinks are detected from `archive_entry_hardlink` **before**
    /// the file type is consulted, because libarchive reports a hardlink as `AE_IFREG`.
    ///
    /// SAFETY (for callers): as [Reader::pathname_bytes].
    unsafe fn metadata(entry: *mut sys::ArchiveEntry) -> Result<EntryMetadata, ArchiveError> {
        // SAFETY: forwarded from this function's own contract.
        let raw_name = unsafe { Self::pathname_bytes(entry) }?;
        let (path, name_lossy) = match std::str::from_utf8(raw_name) {
            Ok(name) => (name.to_string(), false),
            Err(_) => (String::from_utf8_lossy(raw_name).into_owned(), true),
        };
        // SAFETY: `entry` is valid per the contract; every accessor below reads a field of the
        // entry libarchive owns, and the two string accessors return null or a NUL-terminated
        // string owned by the same entry, copied out before this function returns.
        unsafe {
            let lossy = |ptr: *const std::os::raw::c_char| -> Option<String> {
                if ptr.is_null() {
                    None
                } else {
                    Some(CStr::from_ptr(ptr).to_string_lossy().into_owned())
                }
            };
            let hardlink = lossy(sys::archive_entry_hardlink(entry));
            let (kind, link_target) = if hardlink.is_some() {
                (EntryKind::Hardlink, hardlink)
            } else {
                match sys::archive_entry_filetype(entry) & AE_IFMT {
                    AE_IFDIR => (EntryKind::Directory, None),
                    AE_IFREG => (EntryKind::File, None),
                    AE_IFLNK => (EntryKind::Symlink, lossy(sys::archive_entry_symlink(entry))),
                    _ => (EntryKind::Other, None),
                }
            };
            let uncompressed = if sys::archive_entry_size_is_set(entry) != 0 {
                u64::try_from(sys::archive_entry_size(entry)).ok()
            } else {
                None
            };
            let mtime = if sys::archive_entry_mtime_is_set(entry) != 0 {
                Some(widen_time(sys::archive_entry_mtime(entry)))
            } else {
                None
            };
            Ok(EntryMetadata {
                path,
                name_lossy,
                kind,
                link_target,
                uncompressed,
                compressed: None,
                mtime,
                mode: sys::archive_entry_perm(entry),
                encrypted_data: sys::archive_entry_is_data_encrypted(entry) != 0,
                encrypted_metadata: sys::archive_entry_is_metadata_encrypted(entry) != 0,
            })
        }
    }

    /// Advances to the next entry as an [ArchiveEntry], for the simple listing and the lookups.
    fn next_entry(&mut self) -> Result<Option<ArchiveEntry>, ArchiveError> {
        match self.next_header()? {
            // SAFETY: `entry` was just returned by `next_header` on this reader.
            Some(entry) => Ok(Some(unsafe { Self::listing_entry(entry) }?)),
            None => Ok(None),
        }
    }

    /// Reads the CURRENT entry's (the one [Reader::next_header] most recently returned) full body.
    /// Must be called at most once per entry, before the next [Reader::next_header] call.
    fn read_current_entry_data(&mut self) -> Result<Vec<u8>, ArchiveError> {
        let mut data = Vec::new();
        let mut buf = [0u8; 64 * 1024];
        loop {
            // SAFETY: `self.raw` is valid and open; `buf` is a plain stack array and
            // `archive_read_data` writes at most `buf.len()` bytes into it, matching the `len`
            // argument passed.
            let read = unsafe {
                sys::archive_read_data(self.raw, buf.as_mut_ptr() as *mut c_void, buf.len())
            };
            if read < 0 {
                self.check(read as c_int)?;
                // `check` only returns `Ok(())` for OK/EOF/WARN, none of which a negative `read`
                // is, so this is unreachable in practice; kept as a safety net over `unreachable!()`.
                return Err(ArchiveError::Fatal(format!(
                    "archive_read_data returned {read} without a matching error status"
                )));
            }
            if read == 0 {
                return Ok(data);
            }
            data.extend_from_slice(&buf[..read as usize]);
        }
    }

    /// Streams the CURRENT entry's body into `out` block by block (`archive_read_data_block`, zero
    /// copy out of libarchive's own buffers), enforcing `limits` against the bytes actually
    /// produced *before* each block is written, so nothing past a cap ever reaches `out`. Holes
    /// in a sparse entry (a block whose offset is past what has been written, or a final EOF
    /// offset past it) are written as zeros, so the output is byte-exact and sized as the entry
    /// declares. Returns the bytes written for this entry; `running_total` accumulates across
    /// entries for the total cap.
    fn stream_current_entry_data(
        &mut self,
        out: &mut File,
        entry: &EntryMetadata,
        limits: &ExtractLimits,
        running_total: &mut u64,
    ) -> Result<u64, ArchiveError> {
        // The per-entry cap: the limit, or the entry's own declared size if that is smaller --
        // data past what the header declared is a header that lied.
        let declared = entry.uncompressed;
        let cap = declared.map_or(limits.max_file_bytes, |d| d.min(limits.max_file_bytes));
        let mut written: u64 = 0;

        // Accounts `more` bytes about to be produced for this entry against every cap, naming
        // the rule that stops it.
        let mut account = |written: u64, more: u64| -> Result<(), ArchiveError> {
            let next = written.saturating_add(more);
            if next > cap {
                let rule = if declared.is_some_and(|d| next > d) {
                    "declared"
                } else {
                    "file"
                };
                return Err(ArchiveError::LimitExceeded {
                    entry: entry.path.clone(),
                    rule,
                });
            }
            let total = running_total.saturating_add(more);
            if total > limits.max_total_uncompressed_bytes {
                return Err(ArchiveError::LimitExceeded {
                    entry: entry.path.clone(),
                    rule: "total",
                });
            }
            *running_total = total;
            Ok(())
        };

        loop {
            let mut buff: *const c_void = std::ptr::null();
            let mut size: usize = 0;
            let mut offset: sys::LaInt64T = 0;
            // SAFETY: `self.raw` is valid, open and positioned in an entry's data; the three
            // out-parameters are plain locals libarchive fills in, and `buff` then points into
            // storage libarchive owns until the next read call on this same handle -- the slice
            // built from it below is consumed (written out) before any such call.
            let status = unsafe {
                sys::archive_read_data_block(self.raw, &mut buff, &mut size, &mut offset)
            };
            let offset = u64::try_from(offset).map_err(|_| {
                ArchiveError::Fatal(format!(
                    "negative data offset {offset} in entry {:?}",
                    entry.path
                ))
            })?;
            if status == ARCHIVE_EOF {
                // A trailing hole in a sparse entry: the EOF block's offset is the entry's full
                // size (tar reports `disk_size`), so extend with zeros up to it.
                if offset > written {
                    account(written, offset - written)?;
                    write_zeros(out, offset - written, &entry.path)?;
                    written = offset;
                }
                break;
            }
            self.check(status)?;
            if offset < written {
                return Err(ArchiveError::Fatal(format!(
                    "data blocks out of order in entry {:?} (offset {offset} after {written} bytes)",
                    entry.path
                )));
            }
            if offset > written {
                account(written, offset - written)?;
                write_zeros(out, offset - written, &entry.path)?;
                written = offset;
            }
            if size == 0 {
                continue;
            }
            account(written, size as u64)?;
            // SAFETY: `archive_read_data_block` returned OK/WARN with `size > 0`, so `buff`
            // points at `size` readable bytes libarchive owns until the next read call.
            let block = unsafe { std::slice::from_raw_parts(buff as *const u8, size) };
            out.write_all(block)
                .map_err(|e| write_error(&entry.path, e))?;
            written += size as u64;
        }
        out.flush().map_err(|e| write_error(&entry.path, e))?;
        Ok(written)
    }
}

fn write_error(path: &str, error: std::io::Error) -> ArchiveError {
    ArchiveError::Fatal(format!("writing the destination for {path:?}: {error}"))
}

/// Writes `count` zero bytes to `out` in bounded chunks (a sparse hole made explicit).
fn write_zeros(out: &mut File, mut count: u64, path: &str) -> Result<(), ArchiveError> {
    static ZEROS: [u8; 64 * 1024] = [0u8; 64 * 1024];
    while count > 0 {
        let chunk = usize::try_from(count.min(ZEROS.len() as u64)).unwrap_or(ZEROS.len());
        out.write_all(&ZEROS[..chunk])
            .map_err(|e| write_error(path, e))?;
        count -= chunk as u64;
    }
    Ok(())
}

impl Drop for Reader {
    fn drop(&mut self) {
        // SAFETY: `self.raw` was allocated by `archive_read_new` in `Reader::open_positioned` and
        // is never freed anywhere else; `Reader` has no `Clone`, so this runs at most once per
        // handle.
        unsafe {
            sys::archive_read_free(self.raw);
        }
    }
}

/// Lists every entry in the archive at `fd`, without reading any entry's data. `fd` must be a
/// regular file (see the crate doc); it is rewound to byte 0 first and left wherever libarchive
/// stopped. Fails with [ArchiveError::NonUtf8Path] on a name that is not UTF-8 -- [inspect] is the
/// listing that never does.
pub fn entries(fd: RawFd) -> Result<Vec<ArchiveEntry>, ArchiveError> {
    let mut reader = Reader::open_fd(fd)?;
    let mut result = Vec::new();
    while let Some(entry) = reader.next_entry()? {
        result.push(entry);
    }
    Ok(result)
}

/// Reads one entry's full data by path, scanning forward from byte 0 of `fd` (a regular file, see
/// the crate doc). Returns `Ok(None)` if no entry with exactly this path exists -- a normal,
/// expected outcome, not an error. Callers that only need "does this path exist" without its data
/// should use [entries] instead: this function pays for a full read of every entry's body up to
/// and including the match. For a bounded write to a destination, use [extract].
pub fn read_entry(fd: RawFd, path: &str) -> Result<Option<Vec<u8>>, ArchiveError> {
    let mut reader = Reader::open_fd(fd)?;
    while let Some(entry) = reader.next_entry()? {
        if entry.path == path {
            return Ok(Some(reader.read_current_entry_data()?));
        }
    }
    Ok(None)
}

/// Names the compression filters libarchive chose for the archive at `fd` (a regular file, see
/// the crate doc), the one feeding the format reader first (e.g. `"lz4"`) and libarchive's own
/// `"none"` filter (raw I/O against `fd`) last, so an uncompressed archive is just `["none"]`. A
/// codec libarchive was built without still bids, but by shelling out to an external program, and
/// then names itself `"Program: <command>"` -- which is what lets a test prove a backend really is
/// compiled in rather than merely tolerated. [Inspection::filters] is the same list without
/// `"none"`.
pub fn filter_names(fd: RawFd) -> Result<Vec<String>, ArchiveError> {
    let reader = Reader::open_fd(fd)?;
    Ok(reader.filter_names())
}

/// One forward header pass over the archive at `fd` (a regular file, see the crate doc), never
/// reading any entry's data: every entry's [EntryMetadata], the format family, the filter chain
/// and the encryption verdict. Uses only [Limits::max_listing_entries] of `limits` -- past it the
/// result is `LimitExceeded { entry, rule: "listing" }`, a memory bound for the decoder process,
/// not a policy verdict ([inspect_with_policy] gives that). Non-UTF-8 names are decoded lossily
/// and flagged, never an error.
pub fn inspect(fd: RawFd, limits: &Limits) -> Result<Inspection, ArchiveError> {
    let mut reader = Reader::open_fd(fd)?;
    let mut entries = Vec::new();
    let mut format: Option<(u32, Option<String>)> = None;
    loop {
        let next = reader.next_header()?;
        if format.is_none() {
            // After the first header, or EOF for an empty archive (`ARCHIVE_FORMAT_EMPTY`).
            format = Some((reader.format_code(), reader.format_name()));
        }
        let Some(entry) = next else {
            break;
        };
        // SAFETY: `entry` was just returned by `next_header` on this reader.
        let metadata = unsafe { Reader::metadata(entry) }?;
        if entries.len() >= limits.max_listing_entries {
            return Err(ArchiveError::LimitExceeded {
                entry: metadata.path,
                rule: "listing",
            });
        }
        entries.push(metadata);
    }
    let (format_code, format_name) = format.unwrap_or((0, None));
    Ok(Inspection {
        archive_bytes: reader.archive_bytes,
        format_code,
        format_name,
        filters: reader
            .filter_names()
            .into_iter()
            .filter(|name| name != "none")
            .collect(),
        has_encrypted_entries: reader.has_encrypted_entries(),
        entries,
    })
}

/// [inspect], then the extraction [policy] over what it found: `evaluate(archive_bytes,
/// &entries, limits)`. The `Inspection` is returned alongside the verdict so a caller never
/// inspects twice.
pub fn inspect_with_policy(
    fd: RawFd,
    limits: &Limits,
) -> Result<(Inspection, Decision), ArchiveError> {
    let inspection = inspect(fd, limits)?;
    let decision = policy::evaluate(inspection.archive_bytes, &inspection.entries, limits);
    Ok((inspection, decision))
}

/// Streams the selected entries of the archive at `fd` (a regular file, see the crate doc) into
/// descriptors `dest` supplies, one forward pass, enforcing `limits` against the bytes actually
/// produced: an entry whose data exceeds [ExtractLimits::max_file_bytes] or its own declared
/// size, a running total past [ExtractLimits::max_total_uncompressed_bytes], or more than
/// [ExtractLimits::max_entries] selected entries stops the whole extraction with
/// [ArchiveError::LimitExceeded] naming the entry and the rule. Whatever was written before a
/// failure stays: the caller owns cleanup, and this function never deletes.
///
/// Symlinks and hardlinks are never materialised (SAF cannot create them) -- they are counted in
/// [ExtractReport::skipped_links] and `dest` is not consulted; `Other`-kind entries (device
/// nodes, fifos) likewise go uncounted in [ExtractReport::skipped]. Entries not selected are
/// passed over without reading their data. Names that are not UTF-8 are decoded lossily, the same
/// way [inspect] reports them, so a path taken from an [Inspection] matches its entry here.
pub fn extract(
    fd: RawFd,
    selection: &Selection,
    limits: &ExtractLimits,
    dest: &mut dyn DestinationProvider,
) -> Result<ExtractReport, ArchiveError> {
    let mut reader = Reader::open_fd(fd)?;
    let wanted: Option<HashSet<String>> = match selection {
        Selection::All => None,
        Selection::Paths(paths) => Some(
            paths
                .iter()
                .map(|path| policy::normalized_path_key(path))
                .collect(),
        ),
    };
    let mut matched: HashSet<String> = HashSet::new();
    let mut report = ExtractReport::default();
    let mut selected: usize = 0;
    let mut running_total: u64 = 0;

    while let Some(entry) = reader.next_header()? {
        // SAFETY: `entry` was just returned by `next_header` on this reader.
        let metadata = unsafe { Reader::metadata(entry) }?;
        if let Some(wanted) = &wanted {
            let key = policy::normalized_path_key(&metadata.path);
            if !wanted.contains(&key) {
                continue;
            }
            matched.insert(key);
        }
        selected += 1;
        if selected > limits.max_entries {
            return Err(ArchiveError::LimitExceeded {
                entry: metadata.path,
                rule: "entries",
            });
        }
        match metadata.kind {
            EntryKind::Symlink | EntryKind::Hardlink => {
                report.skipped_links += 1;
                continue;
            }
            EntryKind::Other => {
                report.skipped += 1;
                continue;
            }
            EntryKind::File | EntryKind::Directory => {}
        }
        let listing = ArchiveEntry::from_metadata(&metadata);
        let written = match dest.open(&listing)? {
            None => {
                report.skipped += 1;
                continue;
            }
            Some(out_fd) => {
                // The provider owns this descriptor: written to and flushed, never closed.
                let mut out = borrow_fd(out_fd.as_raw_fd());
                reader.stream_current_entry_data(&mut out, &metadata, limits, &mut running_total)?
            }
        };
        dest.done(&listing, written)?;
        report.entries_written += 1;
        report.bytes_written += written;
    }

    if let Selection::Paths(paths) = selection {
        report.missing = paths
            .iter()
            .filter(|path| !matched.contains(&policy::normalized_path_key(path)))
            .cloned()
            .collect();
    }
    Ok(report)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs::File;
    use std::io::Write;
    use std::os::unix::io::AsRawFd;
    use std::path::Path;
    use std::path::PathBuf;
    use std::process::Command;

    /// Builds a real, byte-correct `ar` archive via the system `ar` tool (part of binutils,
    /// present on every Ubuntu CI runner and this workspace's own toolchain) rather than
    /// hand-encoding `ar`'s binary header format: a hand-rolled header that happened to be
    /// internally consistent but subtly wrong against the real format would make this test
    /// validate nothing. `ar` needs no compression codec, matching this task's own zero-codec
    /// scope (see this file's own module doc comment).
    pub(crate) fn build_ar_fixture(dir: &Path, entries: &[(&str, &[u8])]) -> PathBuf {
        for (name, contents) in entries {
            File::create(dir.join(name))
                .unwrap()
                .write_all(contents)
                .unwrap();
        }
        let archive_path = dir.join("fixture.a");
        let status = Command::new("ar")
            .arg("rc")
            .arg(&archive_path)
            .args(entries.iter().map(|(name, _)| *name))
            .current_dir(dir)
            .status()
            .expect("the `ar` tool must be available to build this test's fixture");
        assert!(status.success(), "ar rc failed building the test fixture");
        archive_path
    }

    /// Opens one of the committed fixtures under `core/fixtures/`, generated by
    /// `tools/fixtures/make_compression_fixtures.py` -- whose `ENTRIES` are the same `hello.txt`/
    /// `second.txt` pair [build_ar_fixture]'s callers use, so the literals asserted against a
    /// compressed fixture below are the same ones asserted against the `ar` archive.
    pub(crate) fn open_fixture(name: &str) -> File {
        let path = Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("../../fixtures")
            .join(name);
        File::open(&path).unwrap_or_else(|e| panic!("opening fixture {}: {e}", path.display()))
    }

    #[test]
    fn entries_lists_every_member_without_reading_data() {
        let dir = tempdir();
        let archive_path = build_ar_fixture(
            dir.path(),
            &[
                ("hello.txt", b"hello world"),
                ("second.txt", b"more data, a bit longer"),
            ],
        );
        let file = File::open(&archive_path).unwrap();
        let listed = entries(file.as_raw_fd()).unwrap();
        let names: Vec<&str> = listed.iter().map(|e| e.path.as_str()).collect();
        assert_eq!(names, vec!["hello.txt", "second.txt"]);
        assert_eq!(listed[0].size, 11);
        assert_eq!(listed[1].size, 23);
        assert!(!listed[0].is_directory);
    }

    #[test]
    fn read_entry_returns_the_exact_original_bytes() {
        let dir = tempdir();
        let archive_path = build_ar_fixture(dir.path(), &[("hello.txt", b"hello world")]);
        let file = File::open(&archive_path).unwrap();
        let data = read_entry(file.as_raw_fd(), "hello.txt").unwrap();
        assert_eq!(data, Some(b"hello world".to_vec()));
    }

    #[test]
    fn read_entry_returns_none_for_a_missing_path() {
        let dir = tempdir();
        let archive_path = build_ar_fixture(dir.path(), &[("hello.txt", b"hello world")]);
        let file = File::open(&archive_path).unwrap();
        let data = read_entry(file.as_raw_fd(), "does-not-exist.txt").unwrap();
        assert_eq!(data, None);
    }

    #[test]
    fn an_uncompressed_archive_has_only_the_none_filter() {
        let dir = tempdir();
        let archive_path = build_ar_fixture(dir.path(), &[("hello.txt", b"hello world")]);
        let file = File::open(&archive_path).unwrap();
        assert_eq!(filter_names(file.as_raw_fd()).unwrap(), vec!["none"]);
    }

    #[test]
    fn lz4_sample_entries_lists_every_member() {
        let file = open_fixture("sample.tar.lz4");
        let listed = entries(file.as_raw_fd()).unwrap();
        assert_eq!(
            listed,
            vec![
                ArchiveEntry {
                    path: "hello.txt".to_string(),
                    size: 11,
                    is_directory: false,
                },
                ArchiveEntry {
                    path: "second.txt".to_string(),
                    size: 23,
                    is_directory: false,
                },
            ]
        );
    }

    #[test]
    fn lz4_sample_read_entry_returns_the_exact_original_bytes() {
        let file = open_fixture("sample.tar.lz4");
        let data = read_entry(file.as_raw_fd(), "hello.txt").unwrap();
        assert_eq!(data, Some(b"hello world".to_vec()));
        let file = open_fixture("sample.tar.lz4");
        let data = read_entry(file.as_raw_fd(), "second.txt").unwrap();
        assert_eq!(data, Some(b"more data, a bit longer".to_vec()));
    }

    #[test]
    fn lz4_sample_is_decoded_by_the_compiled_in_lz4_filter() {
        let file = open_fixture("sample.tar.lz4");
        assert_eq!(filter_names(file.as_raw_fd()).unwrap(), vec!["lz4", "none"]);
    }

    #[test]
    fn lz4_truncated_is_a_fatal_error_not_a_panic() {
        let file = open_fixture("truncated.tar.lz4");
        assert!(matches!(
            entries(file.as_raw_fd()),
            Err(ArchiveError::Fatal(_))
        ));
        let file = open_fixture("truncated.tar.lz4");
        assert!(matches!(
            read_entry(file.as_raw_fd(), "second.txt"),
            Err(ArchiveError::Fatal(_))
        ));
    }

    #[test]
    fn zstd_sample_entries_lists_every_member() {
        let file = open_fixture("sample.tar.zst");
        let listed = entries(file.as_raw_fd()).unwrap();
        assert_eq!(
            listed,
            vec![
                ArchiveEntry {
                    path: "hello.txt".to_string(),
                    size: 11,
                    is_directory: false,
                },
                ArchiveEntry {
                    path: "second.txt".to_string(),
                    size: 23,
                    is_directory: false,
                },
            ]
        );
    }

    #[test]
    fn zstd_sample_read_entry_returns_the_exact_original_bytes() {
        let file = open_fixture("sample.tar.zst");
        let data = read_entry(file.as_raw_fd(), "hello.txt").unwrap();
        assert_eq!(data, Some(b"hello world".to_vec()));
        let file = open_fixture("sample.tar.zst");
        let data = read_entry(file.as_raw_fd(), "second.txt").unwrap();
        assert_eq!(data, Some(b"more data, a bit longer".to_vec()));
    }

    #[test]
    fn zstd_sample_is_decoded_by_the_compiled_in_zstd_filter() {
        let file = open_fixture("sample.tar.zst");
        assert_eq!(
            filter_names(file.as_raw_fd()).unwrap(),
            vec!["zstd", "none"]
        );
    }

    #[test]
    fn zstd_truncated_is_a_fatal_error_not_a_panic() {
        let file = open_fixture("truncated.tar.zst");
        assert!(matches!(
            entries(file.as_raw_fd()),
            Err(ArchiveError::Fatal(_))
        ));
        let file = open_fixture("truncated.tar.zst");
        assert!(matches!(
            read_entry(file.as_raw_fd(), "second.txt"),
            Err(ArchiveError::Fatal(_))
        ));
    }

    #[test]
    fn gzip_sample_entries_lists_every_member() {
        let file = open_fixture("sample.tar.gz");
        let listed = entries(file.as_raw_fd()).unwrap();
        assert_eq!(
            listed,
            vec![
                ArchiveEntry {
                    path: "hello.txt".to_string(),
                    size: 11,
                    is_directory: false,
                },
                ArchiveEntry {
                    path: "second.txt".to_string(),
                    size: 23,
                    is_directory: false,
                },
            ]
        );
    }

    #[test]
    fn gzip_sample_read_entry_returns_the_exact_original_bytes() {
        let file = open_fixture("sample.tar.gz");
        let data = read_entry(file.as_raw_fd(), "hello.txt").unwrap();
        assert_eq!(data, Some(b"hello world".to_vec()));
        let file = open_fixture("sample.tar.gz");
        let data = read_entry(file.as_raw_fd(), "second.txt").unwrap();
        assert_eq!(data, Some(b"more data, a bit longer".to_vec()));
    }

    #[test]
    fn gzip_sample_is_decoded_by_the_compiled_in_gzip_filter() {
        let file = open_fixture("sample.tar.gz");
        assert_eq!(
            filter_names(file.as_raw_fd()).unwrap(),
            vec!["gzip", "none"]
        );
    }

    #[test]
    fn gzip_truncated_is_a_fatal_error_not_a_panic() {
        let file = open_fixture("truncated.tar.gz");
        assert!(matches!(
            entries(file.as_raw_fd()),
            Err(ArchiveError::Fatal(_))
        ));
        let file = open_fixture("truncated.tar.gz");
        assert!(matches!(
            read_entry(file.as_raw_fd(), "second.txt"),
            Err(ArchiveError::Fatal(_))
        ));
    }

    #[test]
    fn bzip2_sample_entries_lists_every_member() {
        let file = open_fixture("sample.tar.bz2");
        let listed = entries(file.as_raw_fd()).unwrap();
        assert_eq!(
            listed,
            vec![
                ArchiveEntry {
                    path: "hello.txt".to_string(),
                    size: 11,
                    is_directory: false,
                },
                ArchiveEntry {
                    path: "second.txt".to_string(),
                    size: 23,
                    is_directory: false,
                },
            ]
        );
    }

    #[test]
    fn bzip2_sample_read_entry_returns_the_exact_original_bytes() {
        let file = open_fixture("sample.tar.bz2");
        let data = read_entry(file.as_raw_fd(), "hello.txt").unwrap();
        assert_eq!(data, Some(b"hello world".to_vec()));
        let file = open_fixture("sample.tar.bz2");
        let data = read_entry(file.as_raw_fd(), "second.txt").unwrap();
        assert_eq!(data, Some(b"more data, a bit longer".to_vec()));
    }

    #[test]
    fn bzip2_sample_is_decoded_by_the_compiled_in_bzip2_filter() {
        let file = open_fixture("sample.tar.bz2");
        assert_eq!(
            filter_names(file.as_raw_fd()).unwrap(),
            vec!["bzip2", "none"]
        );
    }

    #[test]
    fn bzip2_truncated_is_a_fatal_error_not_a_panic() {
        let file = open_fixture("truncated.tar.bz2");
        assert!(matches!(
            entries(file.as_raw_fd()),
            Err(ArchiveError::Fatal(_))
        ));
        let file = open_fixture("truncated.tar.bz2");
        assert!(matches!(
            read_entry(file.as_raw_fd(), "second.txt"),
            Err(ArchiveError::Fatal(_))
        ));
    }

    #[test]
    fn xz_sample_entries_lists_every_member() {
        let file = open_fixture("sample.tar.xz");
        let listed = entries(file.as_raw_fd()).unwrap();
        assert_eq!(
            listed,
            vec![
                ArchiveEntry {
                    path: "hello.txt".to_string(),
                    size: 11,
                    is_directory: false,
                },
                ArchiveEntry {
                    path: "second.txt".to_string(),
                    size: 23,
                    is_directory: false,
                },
            ]
        );
    }

    #[test]
    fn xz_sample_read_entry_returns_the_exact_original_bytes() {
        let file = open_fixture("sample.tar.xz");
        let data = read_entry(file.as_raw_fd(), "hello.txt").unwrap();
        assert_eq!(data, Some(b"hello world".to_vec()));
        let file = open_fixture("sample.tar.xz");
        let data = read_entry(file.as_raw_fd(), "second.txt").unwrap();
        assert_eq!(data, Some(b"more data, a bit longer".to_vec()));
    }

    #[test]
    fn xz_sample_is_decoded_by_the_compiled_in_xz_filter() {
        let file = open_fixture("sample.tar.xz");
        assert_eq!(filter_names(file.as_raw_fd()).unwrap(), vec!["xz", "none"]);
    }

    #[test]
    fn xz_truncated_is_a_fatal_error_not_a_panic() {
        let file = open_fixture("truncated.tar.xz");
        assert!(matches!(
            entries(file.as_raw_fd()),
            Err(ArchiveError::Fatal(_))
        ));
        let file = open_fixture("truncated.tar.xz");
        assert!(matches!(
            read_entry(file.as_raw_fd(), "second.txt"),
            Err(ArchiveError::Fatal(_))
        ));
    }

    /// ZIP method 8 (deflate) is what zlib unlocks beyond the gzip filter: without `HAVE_ZLIB_H`
    /// libarchive's ZIP reader lists deflated entries but cannot read their data. No filter is
    /// involved (`["none"]`) -- the decoding happens inside the format reader.
    #[test]
    fn deflated_zip_read_entry_returns_the_exact_original_bytes() {
        let file = open_fixture("sample-deflate.zip");
        assert_eq!(filter_names(file.as_raw_fd()).unwrap(), vec!["none"]);
        let file = open_fixture("sample-deflate.zip");
        let names: Vec<String> = entries(file.as_raw_fd())
            .unwrap()
            .into_iter()
            .map(|e| e.path)
            .collect();
        assert_eq!(names, vec!["hello.txt", "second.txt"]);
        let file = open_fixture("sample-deflate.zip");
        let data = read_entry(file.as_raw_fd(), "hello.txt").unwrap();
        assert_eq!(data, Some(b"hello world".to_vec()));
        let file = open_fixture("sample-deflate.zip");
        let data = read_entry(file.as_raw_fd(), "second.txt").unwrap();
        assert_eq!(data, Some(b"more data, a bit longer".to_vec()));
    }

    /// No format bids on the first header: `Unsupported`, the design's own variant for "not an
    /// archive we can open", rather than `Fatal` ("damaged") -- and never a panic.
    #[test]
    fn a_non_archive_is_unsupported_not_a_panic() {
        let dir = tempdir();
        let path = dir.path().join("not-an-archive");
        File::create(&path)
            .unwrap()
            .write_all(b"this is not an archive of any kind")
            .unwrap();
        let file = File::open(&path).unwrap();
        let result = entries(file.as_raw_fd());
        assert!(
            matches!(result, Err(ArchiveError::Unsupported(ref m)) if m.contains("Unrecognized")),
            "{result:?}"
        );
    }

    /// A tiny, dependency-free stand-in for a `tempfile`-style crate: this crate deliberately adds
    /// no dev-dependency for a handful of tests, matching the project's own "smallest working
    /// thing first" convention. A directory under `std::env::temp_dir()` named with the process
    /// id, an incrementing counter and the current time is unique enough for tests that never run
    /// the same process twice concurrently under the same name, and is removed on drop.
    pub(crate) struct TempDir(PathBuf);
    impl TempDir {
        pub(crate) fn path(&self) -> &Path {
            &self.0
        }
    }
    impl Drop for TempDir {
        fn drop(&mut self) {
            let _ = std::fs::remove_dir_all(&self.0);
        }
    }
    pub(crate) fn tempdir() -> TempDir {
        use std::sync::atomic::AtomicU32;
        use std::sync::atomic::Ordering;
        static COUNTER: AtomicU32 = AtomicU32::new(0);
        let n = COUNTER.fetch_add(1, Ordering::Relaxed);
        let nanos = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap()
            .as_nanos();
        let path = std::env::temp_dir().join(format!(
            "fylz-archive-test-{}-{}-{}",
            std::process::id(),
            n,
            nanos
        ));
        std::fs::create_dir_all(&path).unwrap();
        TempDir(path)
    }
}
