//! M3.2a tests (`docs/agent/DESIGN-M32-SEEKABLE-PFD.md` section 2.8): the engine's seekable
//! contract, discriminated. Each positive runs on one of the committed ZIP/7-Zip/ISO fixtures
//! under `core/fixtures/archives/` (generated by `tools/fixtures/make_archive_fixtures.py`); its
//! negative control feeds the same bytes through `std::io::pipe()` and `Reader::open_unchecked`
//! to show what a non-seekable descriptor would lose -- which is the evidence for refusing pipes
//! at the engine (section 2.1) instead of streaming what libarchive can. Also here: the hostile
//! fixtures refused end to end by the policy, the lossy-name flag on a real ZIP, the per-fixture
//! format codes and names libarchive actually returns, the listing bound on a real 10,001-member
//! file, and (ignored; run by hand) the peak-RSS measurement behind `Limits::max_listing_entries`.

use crate::extract;
use crate::extract_tests::TempProvider;
use crate::inspect;
use crate::inspect_reader;
use crate::inspect_with_policy;
use crate::read_entry;
use crate::read_entry_from;
use crate::tests::open_fixture;
use crate::tests::tempdir;
use crate::ArchiveError;
use crate::EntryKind;
use crate::ExtractLimits;
use crate::Limits;
use crate::Reader;
use crate::Selection;
use std::fs::File;
use std::io::Read;
use std::io::Seek;
use std::io::SeekFrom;
use std::io::Write;
use std::os::unix::io::AsRawFd;
use std::os::unix::net::UnixStream;
use std::path::Path;

const ARCHIVE_FORMAT_TAR: u32 = 0x30000;
const ARCHIVE_FORMAT_ISO9660: u32 = 0x40000;
const ARCHIVE_FORMAT_ZIP: u32 = 0x50000;
const ARCHIVE_FORMAT_7ZIP: u32 = 0xE0000;

/// `make_archive_fixtures.py`'s `FIXED_EPOCH`, stamped on every member of every fixture.
const FIXTURE_MTIME: i64 = 1_577_836_800;

/// The sample tree every non-hostile fixture carries (the script's `TREE`), in sorted order.
const TREE: [(&str, u64); 5] = [
    ("docs/notes/todo.txt", 268),
    ("docs/readme.md", 67),
    ("hello.txt", 11),
    ("images/gradient.bin", 1024),
    ("images/pixel.bin", 256),
];

fn archive_fixture(name: &str) -> File {
    open_fixture(&format!("archives/{name}"))
}

/// A pipe being fed the whole of a fixture from another thread (the ISO is larger than a pipe's
/// buffer, so writing it all up front would block), its write end closed once done.
fn pipe_with_fixture(name: &str) -> std::io::PipeReader {
    let (reader, mut writer) = std::io::pipe().unwrap();
    let mut bytes = Vec::new();
    archive_fixture(name).read_to_end(&mut bytes).unwrap();
    std::thread::spawn(move || {
        // A reader that stops early (an error mid-archive) closes its end; the resulting EPIPE
        // here is expected, not a test failure.
        let _ = writer.write_all(&bytes);
    });
    reader
}

fn file_paths(inspection: &crate::Inspection) -> Vec<(&str, Option<u64>)> {
    inspection
        .entries
        .iter()
        .filter(|e| e.kind == EntryKind::File)
        .map(|e| (e.path.as_str(), e.uncompressed))
        .collect()
}

fn directory_paths(inspection: &crate::Inspection) -> Vec<&str> {
    inspection
        .entries
        .iter()
        .filter(|e| e.kind == EntryKind::Directory)
        .map(|e| e.path.as_str())
        .collect()
}

// ---------------------------------------------------------------------------------------------
// The contract: only regular files.
// ---------------------------------------------------------------------------------------------

#[test]
fn open_refuses_a_pipe_and_a_socket_with_not_seekable() {
    let not_seekable = |result: Result<crate::Inspection, ArchiveError>| match result {
        Err(ArchiveError::NotSeekable(message)) => message,
        other => panic!("expected NotSeekable, got {other:?}"),
    };
    let (reader, _writer) = std::io::pipe().unwrap();
    assert_eq!(
        not_seekable(inspect(reader.as_raw_fd(), &Limits::default())),
        "not seekable (fifo)"
    );
    let (socket, _peer) = UnixStream::pair().unwrap();
    assert_eq!(
        not_seekable(inspect(socket.as_raw_fd(), &Limits::default())),
        "not seekable (socket)"
    );
    // Nothing was read from either: the refusal comes from `fstat`, before libarchive opens.
    let _ = (_writer, _peer);
}

/// Section 2.1's correctness requirement, on the fixture whose central directory libarchive
/// finds by an absolute seek from the end of the file: a descriptor left mid-file (as a Binder
/// dup that some earlier reader moved would be) yields the same inspection as a fresh open.
#[test]
fn inspect_ignores_the_descriptors_initial_offset() {
    let fresh = inspect(
        archive_fixture("sample-cd.zip").as_raw_fd(),
        &Limits::default(),
    )
    .unwrap();
    assert_eq!(fresh.entries.len(), 8);

    let mut moved = archive_fixture("sample-cd.zip");
    let length = moved.metadata().unwrap().len();
    moved.seek(SeekFrom::Start(length / 2)).unwrap();
    assert_eq!(
        inspect(moved.as_raw_fd(), &Limits::default()).unwrap(),
        fresh
    );

    let mut at_end = archive_fixture("sample-cd.zip");
    at_end.seek(SeekFrom::End(0)).unwrap();
    assert_eq!(
        inspect(at_end.as_raw_fd(), &Limits::default()).unwrap(),
        fresh
    );
}

// ---------------------------------------------------------------------------------------------
// ZIP: the seekable reader reads sizes from the central directory.
// ---------------------------------------------------------------------------------------------

/// `sample-streamed.zip` was written to a sink without `seek`: every local header carries zero
/// sizes and bit 3, with the real sizes only in the data descriptor after the data and in the
/// central directory at the end. libarchive's seekable ZIP reader jumps to the central directory
/// first, so from a file every size is known before any data is read; the streaming reader, the
/// only one a pipe gets, reports none of them. `sample-cd.zip` is the control's control: with
/// bit 3 clear its local headers carry sizes, so even the streaming reader reports them.
#[test]
fn streamed_zip_sizes_come_from_the_central_directory_only_when_seekable() {
    let expected: Vec<(&str, Option<u64>)> = TREE.iter().map(|(p, s)| (*p, Some(*s))).collect();
    let expected_dirs = vec!["docs/", "docs/notes/", "images/"];

    let from_file = inspect(
        archive_fixture("sample-streamed.zip").as_raw_fd(),
        &Limits::default(),
    )
    .unwrap();
    assert_eq!(from_file.format_code, ARCHIVE_FORMAT_ZIP);
    assert_eq!(file_paths(&from_file), expected);
    assert_eq!(directory_paths(&from_file), expected_dirs);

    let pipe = pipe_with_fixture("sample-streamed.zip");
    let from_pipe = inspect_reader(
        Reader::open_unchecked(pipe.as_raw_fd()).unwrap(),
        &Limits::default(),
    )
    .unwrap();
    assert_eq!(from_pipe.format_code, ARCHIVE_FORMAT_ZIP);
    // Same names in the same order, but no size for anything, directories included.
    assert_eq!(
        file_paths(&from_pipe),
        TREE.iter().map(|(p, _)| (*p, None)).collect::<Vec<_>>()
    );
    assert!(
        from_pipe.entries.iter().all(|e| e.uncompressed.is_none()),
        "{from_pipe:?}"
    );
    // And the policy, which refuses an entry of unknown size, would refuse the whole archive.
    let decision = crate::policy::evaluate(
        from_file.archive_bytes,
        &from_pipe.entries,
        &Limits::default(),
    );
    assert_eq!(
        decision.reason,
        Some("Archive contains an entry with unknown size.")
    );

    // The control's control: bit 3 clear, so the streaming reader still sees sizes.
    let pipe = pipe_with_fixture("sample-cd.zip");
    let cd_from_pipe = inspect_reader(
        Reader::open_unchecked(pipe.as_raw_fd()).unwrap(),
        &Limits::default(),
    )
    .unwrap();
    assert_eq!(file_paths(&cd_from_pipe), expected);
}

// ---------------------------------------------------------------------------------------------
// 7-Zip: pack streams are behind the header, so data needs a backward seek.
// ---------------------------------------------------------------------------------------------

/// A 7-Zip file ends with its header; entry data sits in pack streams *before* it, so reading
/// any entry means seeking back. From a file both fixtures list and read; from a pipe the
/// COPY-filtered one with a plain header still lists (the header is reached by consuming
/// forward) but every data read fails with libarchive's own "Seek error", and the LZMA2 one,
/// whose header is itself an encoded stream, cannot even list. An `Err`, never a panic.
#[test]
fn seven_zip_entry_data_needs_a_backward_seek() {
    let expected: Vec<(&str, Option<u64>)> = TREE.iter().map(|(p, s)| (*p, Some(*s))).collect();
    for name in ["sample-copy.7z", "sample-lzma2.7z"] {
        let listed = inspect(archive_fixture(name).as_raw_fd(), &Limits::default()).unwrap();
        assert_eq!(listed.format_code, ARCHIVE_FORMAT_7ZIP, "{name}");
        assert_eq!(file_paths(&listed), expected, "{name}");
        // py7zr's `writestr` records no directory members and stamps 0600.
        assert!(directory_paths(&listed).is_empty(), "{name}");
        assert!(listed.entries.iter().all(|e| e.mode == 0o600), "{name}");
        assert_eq!(
            read_entry(archive_fixture(name).as_raw_fd(), "hello.txt").unwrap(),
            Some(b"hello world".to_vec()),
            "{name}"
        );
        assert_eq!(
            read_entry(archive_fixture(name).as_raw_fd(), "images/gradient.bin")
                .unwrap()
                .map(|d| d.len()),
            Some(1024),
            "{name}"
        );

        let pipe = pipe_with_fixture(name);
        let result = Reader::open_unchecked(pipe.as_raw_fd())
            .and_then(|reader| read_entry_from(reader, "hello.txt"));
        assert!(
            matches!(result, Err(ArchiveError::Fatal(ref m)) if m == "Seek error"),
            "{name}: {result:?}"
        );
    }

    // The plain-header COPY fixture lists from a pipe (forward consume reaches the header)...
    let pipe = pipe_with_fixture("sample-copy.7z");
    let listed = inspect_reader(
        Reader::open_unchecked(pipe.as_raw_fd()).unwrap(),
        &Limits::default(),
    )
    .unwrap();
    assert_eq!(file_paths(&listed), expected);
    // ...the encoded-header LZMA2 fixture does not even do that.
    let pipe = pipe_with_fixture("sample-lzma2.7z");
    let result = inspect_reader(
        Reader::open_unchecked(pipe.as_raw_fd()).unwrap(),
        &Limits::default(),
    );
    assert!(
        matches!(result, Err(ArchiveError::Fatal(ref m)) if m == "Seek error"),
        "{result:?}"
    );
}

/// py7zr can encrypt the header itself (`header_encryption=True`): libarchive recognises the
/// format, then fails reading the first header with its own "encrypted, but currently not
/// supported" -- `Unsupported`, the outcome the app shows as "not an archive we can open".
#[test]
fn seven_zip_encrypted_header_is_unsupported() {
    let result = inspect(
        archive_fixture("sample-encrypted-header.7z").as_raw_fd(),
        &Limits::default(),
    );
    assert!(
        matches!(
            result,
            Err(ArchiveError::Unsupported(ref m))
                if m == "The archive header is encrypted, but currently not supported"
        ),
        "{result:?}"
    );
}

// ---------------------------------------------------------------------------------------------
// ISO 9660: Rock Ridge names, nested directories, and the synthesized root.
// ---------------------------------------------------------------------------------------------

/// The image was written with Joliet and Rock Ridge; libarchive picks the Rock Ridge names
/// (`docs/readme.md`, not `DOCS/README.MD;1`), lists directories before their contents in
/// extent order, and lists the image's root as a directory named `.` -- which `inspect` drops
/// (`is_archive_root`), so the policy passes the image instead of refusing its `.` segment.
///
/// No pipe-fed negative control: libarchive reads an in-order ISO as one forward pass, using
/// `lseek` only to skip extents it does not need, and pycdlib has no API for out-of-order
/// extents (the one case that seeks backwards). The same image therefore lists *and* reads from
/// a pipe too; asserted below so the record is a fact, not a claim.
#[test]
fn iso_lists_nested_directories_with_rock_ridge_names() {
    let inspection = inspect(
        archive_fixture("sample.iso").as_raw_fd(),
        &Limits::default(),
    )
    .unwrap();
    assert_eq!(inspection.format_code, ARCHIVE_FORMAT_ISO9660);
    assert_eq!(
        inspection.format_name.as_deref(),
        Some("ISO9660 with Rockridge extensions")
    );
    assert_eq!(inspection.has_encrypted_entries, None);
    assert_eq!(
        directory_paths(&inspection),
        vec!["docs", "images", "docs/notes"]
    );
    let mut files = file_paths(&inspection);
    files.sort();
    assert_eq!(
        files,
        TREE.iter().map(|(p, s)| (*p, Some(*s))).collect::<Vec<_>>()
    );
    assert!(inspection
        .entries
        .iter()
        .all(|e| e.mtime == Some(FIXTURE_MTIME)));
    assert!(!inspection.entries.iter().any(|e| e.path == "."));
    assert_eq!(inspection.entries.len(), 8);

    let (_, decision) = inspect_with_policy(
        archive_fixture("sample.iso").as_raw_fd(),
        &Limits::default(),
    )
    .unwrap();
    assert!(decision.allowed, "{decision:?}");

    assert_eq!(
        read_entry(
            archive_fixture("sample.iso").as_raw_fd(),
            "docs/notes/todo.txt"
        )
        .unwrap()
        .map(|d| d.len()),
        Some(268)
    );

    // extract() skips the root the same way, and writes every file.
    let dir = tempdir();
    let mut provider = TempProvider::new(dir.path());
    let report = extract(
        archive_fixture("sample.iso").as_raw_fd(),
        &Selection::All,
        &ExtractLimits::default(),
        &mut provider,
    )
    .unwrap();
    assert_eq!(report.entries_written, 5);
    assert_eq!(report.bytes_written, 268 + 67 + 11 + 1024 + 256);
    assert!(!provider.offered_paths().contains(&"."));
    assert_eq!(provider.read("hello.txt"), b"hello world");

    // The honest record: in-order ISO needs no backward seek, so a pipe lists and reads too.
    let pipe = pipe_with_fixture("sample.iso");
    let from_pipe = inspect_reader(
        Reader::open_unchecked(pipe.as_raw_fd()).unwrap(),
        &Limits::default(),
    )
    .unwrap();
    assert_eq!(from_pipe.entries.len(), 8);
    let pipe = pipe_with_fixture("sample.iso");
    assert_eq!(
        read_entry_from(
            Reader::open_unchecked(pipe.as_raw_fd()).unwrap(),
            "hello.txt"
        )
        .unwrap(),
        Some(b"hello world".to_vec())
    );
}

// ---------------------------------------------------------------------------------------------
// Hostile fixtures, end to end through the policy.
// ---------------------------------------------------------------------------------------------

#[test]
fn hostile_fixtures_are_refused() {
    let cases = [
        (
            "hostile/zip-slip.zip",
            "Archive contains an unsafe path segment.",
            "../evil",
        ),
        (
            "hostile/absolute-path.zip",
            "Archive contains an absolute or invalid path.",
            "/etc/passwd",
        ),
        (
            "hostile/symlink-escape.tar",
            "Archive contains a link that escapes the extraction folder.",
            "escape",
        ),
        (
            "hostile/many-entries.tar.zst",
            "Archive contains too many entries.",
            "e10000",
        ),
    ];
    for (name, reason, telltale) in cases {
        let (inspection, decision) =
            inspect_with_policy(archive_fixture(name).as_raw_fd(), &Limits::default()).unwrap();
        assert!(!decision.allowed, "{name}");
        assert_eq!(decision.reason, Some(reason), "{name}");
        // libarchive hands the hostile name through verbatim; nothing normalises it away.
        assert!(
            inspection.entries.iter().any(|e| e.path == telltale),
            "{name}: {telltale} not listed"
        );
    }
    // The link fixture's target is what the rule judged.
    let inspection = inspect(
        archive_fixture("hostile/symlink-escape.tar").as_raw_fd(),
        &Limits::default(),
    )
    .unwrap();
    let link = &inspection.entries[1];
    assert_eq!(link.kind, EntryKind::Symlink);
    assert_eq!(link.link_target.as_deref(), Some("/etc/passwd"));
    // 10,001 zero-length members: one over `max_entries`, and well under the listing bound.
    let inspection = inspect(
        archive_fixture("hostile/many-entries.tar.zst").as_raw_fd(),
        &Limits::default(),
    )
    .unwrap();
    assert_eq!(inspection.entries.len(), 10_001);
    assert_eq!(inspection.filters, vec!["zstd"]);
}

/// The same 10,001-member file against a listing bound below its count: `inspect` stops with
/// the `"listing"` rule naming the first entry past the bound, rather than collecting on.
#[test]
fn max_listing_entries_stops_the_pass_on_a_real_file() {
    let limits = Limits {
        max_listing_entries: 10_000,
        ..Limits::default()
    };
    let result = inspect(
        archive_fixture("hostile/many-entries.tar.zst").as_raw_fd(),
        &limits,
    );
    assert!(
        matches!(
            result,
            Err(ArchiveError::LimitExceeded { ref entry, rule: "listing" }) if entry == "e10000"
        ),
        "{result:?}"
    );
}

// ---------------------------------------------------------------------------------------------
// Lossy names on a real ZIP.
// ---------------------------------------------------------------------------------------------

/// CRC-32 (reflected, polynomial 0xEDB88320) as ZIP stores it; bitwise, since this is a test.
fn crc32(data: &[u8]) -> u32 {
    let mut crc: u32 = 0xFFFF_FFFF;
    for &byte in data {
        crc ^= u32::from(byte);
        for _ in 0..8 {
            crc = if crc & 1 != 0 {
                (crc >> 1) ^ 0xEDB8_8320
            } else {
                crc >> 1
            };
        }
    }
    !crc
}

/// A ZIP with stored entries and *raw* names: `zipfile` cannot write a non-UTF-8 name (it
/// encodes every non-ASCII name as UTF-8 and sets bit 11), which is exactly the legacy shape a
/// CP437 archiver produced, so it is built by hand here. Local header, central directory, end
/// record; DOS date 1980-01-01, no extra fields, bit 11 clear.
pub(crate) fn build_stored_zip(dir: &Path, entries: &[(&[u8], &[u8])]) -> std::path::PathBuf {
    let mut out = Vec::new();
    let mut central = Vec::new();
    for (name, data) in entries {
        let offset = out.len() as u32;
        let crc = crc32(data);
        let size = data.len() as u32;
        let name_len = name.len() as u16;
        out.extend_from_slice(&0x0403_4B50u32.to_le_bytes());
        out.extend_from_slice(&20u16.to_le_bytes()); // version needed
        out.extend_from_slice(&0u16.to_le_bytes()); // flags: bit 11 clear, so the name is "CP437"
        out.extend_from_slice(&0u16.to_le_bytes()); // method: stored
        out.extend_from_slice(&0u16.to_le_bytes()); // DOS time
        out.extend_from_slice(&0x0021u16.to_le_bytes()); // DOS date 1980-01-01
        out.extend_from_slice(&crc.to_le_bytes());
        out.extend_from_slice(&size.to_le_bytes());
        out.extend_from_slice(&size.to_le_bytes());
        out.extend_from_slice(&name_len.to_le_bytes());
        out.extend_from_slice(&0u16.to_le_bytes());
        out.extend_from_slice(name);
        out.extend_from_slice(data);

        central.extend_from_slice(&0x0201_4B50u32.to_le_bytes());
        central.extend_from_slice(&0x0314u16.to_le_bytes()); // made by: Unix, 2.0
        central.extend_from_slice(&20u16.to_le_bytes());
        central.extend_from_slice(&0u16.to_le_bytes());
        central.extend_from_slice(&0u16.to_le_bytes());
        central.extend_from_slice(&0u16.to_le_bytes());
        central.extend_from_slice(&0x0021u16.to_le_bytes());
        central.extend_from_slice(&crc.to_le_bytes());
        central.extend_from_slice(&size.to_le_bytes());
        central.extend_from_slice(&size.to_le_bytes());
        central.extend_from_slice(&name_len.to_le_bytes());
        central.extend_from_slice(&0u16.to_le_bytes()); // extra
        central.extend_from_slice(&0u16.to_le_bytes()); // comment
        central.extend_from_slice(&0u16.to_le_bytes()); // disk
        central.extend_from_slice(&0u16.to_le_bytes()); // internal attributes
        central.extend_from_slice(&(0o644u32 << 16).to_le_bytes());
        central.extend_from_slice(&offset.to_le_bytes());
        central.extend_from_slice(name);
    }
    let central_offset = out.len() as u32;
    let central_size = central.len() as u32;
    out.extend_from_slice(&central);
    out.extend_from_slice(&0x0605_4B50u32.to_le_bytes());
    out.extend_from_slice(&0u16.to_le_bytes());
    out.extend_from_slice(&0u16.to_le_bytes());
    out.extend_from_slice(&(entries.len() as u16).to_le_bytes());
    out.extend_from_slice(&(entries.len() as u16).to_le_bytes());
    out.extend_from_slice(&central_size.to_le_bytes());
    out.extend_from_slice(&central_offset.to_le_bytes());
    out.extend_from_slice(&0u16.to_le_bytes());
    let path = dir.join("legacy.zip");
    File::create(&path).unwrap().write_all(&out).unwrap();
    path
}

/// A legacy ZIP whose entry name holds the CP437 byte 0x82 (`é` in that code page) inspects
/// with the name decoded lossily and flagged, and the policy still judges its structure --
/// never `NonUtf8Path`, which only the exact-match lookups keep.
#[test]
fn lossy_names_are_flagged_not_fatal() {
    let dir = tempdir();
    let path = build_stored_zip(
        dir.path(),
        &[
            (b"caf\x82.txt", b"cp437 name"),
            (b"plain.txt", b"ascii name"),
        ],
    );
    let file = File::open(&path).unwrap();
    let (inspection, decision) = inspect_with_policy(file.as_raw_fd(), &Limits::default()).unwrap();
    assert_eq!(inspection.format_code, ARCHIVE_FORMAT_ZIP);
    assert_eq!(inspection.entries.len(), 2);
    let legacy = &inspection.entries[0];
    assert_eq!(legacy.path, "caf\u{FFFD}.txt");
    assert!(legacy.name_lossy);
    assert_eq!(legacy.uncompressed, Some(10));
    assert!(!inspection.entries[1].name_lossy);
    assert!(decision.allowed, "{decision:?}");
    // The strict lookups keep refusing, as documented on `NonUtf8Path` -- `read_entry` too,
    // even for the ASCII-named member, because it scans forward through the legacy name first.
    let file = File::open(&path).unwrap();
    assert!(matches!(
        crate::entries(file.as_raw_fd()),
        Err(ArchiveError::NonUtf8Path)
    ));
    let file = File::open(&path).unwrap();
    assert!(matches!(
        read_entry(file.as_raw_fd(), "plain.txt"),
        Err(ArchiveError::NonUtf8Path)
    ));
    // The hand-built ZIP is a real one, and `extract` names entries the way `inspect` did: the
    // lossy path selects its own member, and both read back byte-exact.
    let file = File::open(&path).unwrap();
    let mut provider = TempProvider::new(dir.path());
    let report = extract(
        file.as_raw_fd(),
        &Selection::Paths(vec!["caf\u{FFFD}.txt".to_string(), "plain.txt".to_string()]),
        &ExtractLimits::default(),
        &mut provider,
    )
    .unwrap();
    assert_eq!(report.entries_written, 2);
    assert!(report.missing.is_empty());
    assert_eq!(provider.read("caf\u{FFFD}.txt"), b"cp437 name");
    assert_eq!(provider.read("plain.txt"), b"ascii name");
}

// ---------------------------------------------------------------------------------------------
// What libarchive actually reports per fixture.
// ---------------------------------------------------------------------------------------------

/// The format family, `archive_format_name` and filter chain libarchive returns for each fixture,
/// copied from a run rather than guessed. `format_name` is informational (for ZIP it names the
/// compression method of whichever entry the reader last positioned on, hence "(uncompressed)"
/// for a deflated archive whose pass ended at EOF, and "(deflation)" for another); decisions key
/// on `format_code` only.
/// One row of [format_code_and_filters_per_fixture]'s table.
struct Observed {
    fixture: &'static str,
    code: u32,
    format_name: &'static str,
    filters: &'static [&'static str],
    encrypted: Option<bool>,
    entries: usize,
}

#[test]
fn format_code_and_filters_per_fixture() {
    let expected = [
        Observed {
            fixture: "sample-cd.zip",
            code: ARCHIVE_FORMAT_ZIP,
            format_name: "ZIP 2.0 (uncompressed)",
            filters: &[],
            encrypted: Some(false),
            entries: 8,
        },
        Observed {
            fixture: "sample-streamed.zip",
            code: ARCHIVE_FORMAT_ZIP,
            format_name: "ZIP 2.0 (uncompressed)",
            filters: &[],
            encrypted: Some(false),
            entries: 8,
        },
        Observed {
            fixture: "sample-copy.7z",
            code: ARCHIVE_FORMAT_7ZIP,
            format_name: "7-Zip",
            filters: &[],
            encrypted: Some(false),
            entries: 5,
        },
        Observed {
            fixture: "sample-lzma2.7z",
            code: ARCHIVE_FORMAT_7ZIP,
            format_name: "7-Zip",
            filters: &[],
            encrypted: Some(false),
            entries: 5,
        },
        Observed {
            fixture: "sample.iso",
            code: ARCHIVE_FORMAT_ISO9660,
            format_name: "ISO9660 with Rockridge extensions",
            filters: &[],
            encrypted: None,
            entries: 8,
        },
        Observed {
            fixture: "hostile/zip-slip.zip",
            code: ARCHIVE_FORMAT_ZIP,
            format_name: "ZIP 2.0 (deflation)",
            filters: &[],
            encrypted: Some(false),
            entries: 2,
        },
        Observed {
            fixture: "hostile/absolute-path.zip",
            code: ARCHIVE_FORMAT_ZIP,
            format_name: "ZIP 2.0 (deflation)",
            filters: &[],
            encrypted: Some(false),
            entries: 2,
        },
        Observed {
            fixture: "hostile/symlink-escape.tar",
            code: ARCHIVE_FORMAT_TAR,
            format_name: "POSIX ustar format",
            filters: &[],
            encrypted: None,
            entries: 2,
        },
        Observed {
            fixture: "hostile/many-entries.tar.zst",
            code: ARCHIVE_FORMAT_TAR,
            format_name: "POSIX ustar format",
            filters: &["zstd"],
            encrypted: None,
            entries: 10_001,
        },
    ];
    for row in expected {
        let name = row.fixture;
        let file = archive_fixture(name);
        let inspection = inspect(file.as_raw_fd(), &Limits::default()).unwrap();
        assert_eq!(inspection.format_code, row.code, "{name}");
        assert_eq!(
            inspection.format_name.as_deref(),
            Some(row.format_name),
            "{name}"
        );
        assert_eq!(inspection.filters, row.filters, "{name}");
        assert_eq!(inspection.has_encrypted_entries, row.encrypted, "{name}");
        assert_eq!(inspection.entries.len(), row.entries, "{name}");
        assert_eq!(
            inspection.archive_bytes,
            file.metadata().unwrap().len(),
            "{name}"
        );
        assert!(
            inspection
                .entries
                .iter()
                .all(|e| e.mtime == Some(FIXTURE_MTIME)),
            "{name}: every member is stamped with the generator's fixed epoch"
        );
        assert!(
            inspection
                .entries
                .iter()
                .all(|e| !e.encrypted_data && !e.encrypted_metadata && !e.name_lossy),
            "{name}"
        );
    }
}

// ---------------------------------------------------------------------------------------------
// The memory bound behind `Limits::max_listing_entries` (run by hand).
// ---------------------------------------------------------------------------------------------

/// `VmHWM` (peak resident set) and `VmRSS` of this process, in KiB, from `/proc/self/status`.
fn rss_kib() -> (u64, u64) {
    let status = std::fs::read_to_string("/proc/self/status").unwrap();
    let field = |key: &str| -> u64 {
        status
            .lines()
            .find(|l| l.starts_with(key))
            .and_then(|l| l.split_whitespace().nth(1))
            .and_then(|v| v.parse().ok())
            .unwrap_or(0)
    };
    (field("VmHWM:"), field("VmRSS:"))
}

/// The measurement `DESIGN-M32-SEEKABLE-PFD.md` section 2.4 asks for: peak RSS of `inspect` on a
/// synthetic 200,000-entry tar (built with Python's `tarfile`, not committed), against the
/// 64 MB threshold above which `max_listing_entries` must drop. Ignored because the fixture is
/// 100 MB and made on demand; run once with
///
///     FYLZ_RSS_TAR=/path/to/rss-200k.tar cargo test -p fylz-archive --lib \
///         peak_rss_of_inspect_on_a_200k_entry_tar -- --ignored --exact --nocapture
///
/// and record the printed figures (and the harness process's own `ru_maxrss`, if measured from
/// outside) in the PROGRESS row.
#[test]
#[ignore]
fn peak_rss_of_inspect_on_a_200k_entry_tar() {
    let path = std::env::var("FYLZ_RSS_TAR")
        .expect("set FYLZ_RSS_TAR to a tar with 200,000 members (see the test's doc comment)");
    let file = File::open(&path).unwrap();
    let (hwm_before, rss_before) = rss_kib();
    let inspection = inspect(file.as_raw_fd(), &Limits::default()).unwrap();
    let (hwm_after, rss_after) = rss_kib();
    println!(
        "entries={} VmHWM before={} KiB after={} KiB (+{} KiB) VmRSS before={} KiB after={} KiB",
        inspection.entries.len(),
        hwm_before,
        hwm_after,
        hwm_after - hwm_before,
        rss_before,
        rss_after
    );
    assert_eq!(inspection.entries.len(), 200_000);
    assert!(
        hwm_after - hwm_before < 64 * 1024,
        "inspect's peak RSS grew by {} KiB, over the 64 MB bound",
        hwm_after - hwm_before
    );
}
